---
kind: pipeline
type: docker
name: update-script

steps:
  - name: Update flake
    image: nixos/nix
    commands:
      - echo "substituters = https://cache.nixos.org/ https://f000.backblazeb2.com/file/cache-chir-rs/" >> /etc/nix/nix.conf
      - echo "trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nixcache:8KKuGz95Pk4UJ5W/Ni+pN+v+LDTkMMFV4yrGmAYgkDg= hydra.nixos.org-1:CNHJZBh9K4tP3EKF6FkkgeVYsS3ohTl+oS0Qa8bezVs=" >> /etc/nix/nix.conf
      - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
      - nix flake update
      - (cd minecraft && ./update.sh)
      - (cd mastodon && ./update.sh)
      - (cd matrix/matrix-media-repo && ./update.sh)
      - (cd art && ./update.sh)
      - nix fmt
  - name: Push git
    image: alpine:latest
    commands:
      - apk add git openssh
      - mkdir ~/.ssh
      - echo "$SSH_KEY" > ~/.ssh/id_ed25519
      - chmod 600 ~/.ssh/id_ed25519
      - echo "git.chir.rs ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICQ77jA9S5qXDFGPLZRsC++AtxiXXeF8gVbkLlglx0GQ" > ~/.ssh/known_hosts
      - echo "git.chir.rs ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDY0pZzNTAqaVqqfC31gYFixFs5KySv0UqvlDEAzEXJMB/pBWkE5GAd5Ik1NxD4QiAVWc2UARdmJEBbYf8mk5JiAv6fjsodJdJVRau4Ax7FtIfbxdFyzBgFery/KUnNIr6cmAWU2Af8JhzrnpEbhe5U3LftYnkdE1lI+iVqaQRARp0qikdzoAl3uMUhbdTxp1/6rtfN6bP2XZCsUx3t3W5ZG1QTQz8l7nrbXZX1TT3pZ2vcUANcMtOxEAwO6lbL210GX63C8XEoE7+4lLxRrSiaq3SkVlG07VspozKEtrrcsqCRNLebiaapmNWVoEq9Wd9VGAEjja5efyU6/HUlRogAOo1WP73UwoQLv5LTFH+ECoHhKS14xfPeXeVG8dbYyh5+CnmiVe43dH1qZw+ceYuYel31f47cAgScbxFvNkct0spK9m9mivnoUmYcxwTc+VbFbmnJvSuZw3a+OEYn9biitP/tTkYFiLZVdPZTxDkvd1oOyuVH9d4RMXbVgNS92/lr2iKFZkyhWMJ61hFMc2tupwmkp5Us5ce42XA0zC/aVY3vYoih/c5Ib0eZF1AEJdB6Bt5dWqITVsB3mip3Jn/mqVBIPTGXT6+FnGSEuL68Dj2yKBD7kj8YO/1SWpkVMy+bfoLXY/usgcaLCxpUu8dDrdrcKExLigCVbi3rdRmg7w==" >> ~/.ssh/known_hosts
      - git remote set-url origin gitea@git.chir.rs:darkkirb/nix-packages.git
      - git config --global 'user.email' 'gitea-bot@chir.rs'
      - git config --global 'user.name' 'Gitea Bot'
      - git add .
      - git commit -am "Update packages"
      - git push --force origin main:update-package
    environment:
      SSH_KEY:
        from_secret: SSH_KEY
  - name: Create pull request
    image: alpine:latest
    commands:
      - apk add jq curl
      - |
        echo '{ "assignee": "DarkKirb", "base": "main", "head": "update-packages", "title": "Update packages" }' | jq '.body = $body' --arg body "$(cat ../pr-message.txt)" | curl -XPOST  'https://git.chir.rs/api/v1/repos/DarkKirb/nix-packages/pulls' -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHORISATION" --data-binary @-
    environment:
      AUTHORISATION:
        from_secret: GITEA_KEY
#trigger:
  #  event:
  #    - cron
  #  cron:
  #    - updater
trigger:
  branch:
    - main
---
kind: pipeline
type: docker
name: notify-hydra

steps:
  - name: Notify hydra
    image: curlimages/curl:latest
    commands:
      - curl --get --data-urlencode "jobsets=darkkirb:nix-packages" https://hydra.chir.rs/api/push
trigger:
  branch:
    - main
