schema = 3

[mod]
  [mod."filippo.io/edwards25519"]
    version = "v1.0.0"
    hash = "sha256-APnPAcmItvtJ5Zsy863lzR2TjEBF9Y66TY1e4M1ap98="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.1.2"
    hash = "sha256-YV9SmXDtmmgQylQUfrUgQLAPfqYexcHxegMBT+IX9qM="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.2"
    hash = "sha256-IVwooaIo46iq7euSSVWTBAdKd+2DUaJ67MtBao1DpBI="
  [mod."github.com/gorilla/mux"]
    version = "v1.8.0"
    hash = "sha256-s905hpzMH9bOLue09E2JmzPXfIS4HhAlgT7g13HCwKE="
  [mod."github.com/gorilla/websocket"]
    version = "v1.5.0"
    hash = "sha256-EYVgkSEMo4HaVrsWKqnsYRp8SSS8gNf7t+Elva02Ofc="
  [mod."github.com/lib/pq"]
    version = "v1.10.6"
    hash = "sha256-8EhFwY/9YH5L/fd6l2beOnC3VvpegRAmCCsnDVJBqBM="
  [mod."github.com/mattn/go-sqlite3"]
    version = "v1.14.14"
    hash = "sha256-9ih+l+JbwfjfpJEjFyO996rJIFFMg7Tfb0SAinp/01I="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.1"
    hash = "sha256-ystDNStxR90j4CK+AMcEQ5oyYFRgWoGdvWlS0XQMDLQ="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.12.2-0.20220613221938-ebd77f036066"
    hash = "sha256-qD+45jMCvRtp99UYCr6C2NpSmAHy8ii85B5Ta9OuftM="
  [mod."github.com/prometheus/client_model"]
    version = "v0.2.0"
    hash = "sha256-LTHxYPRgoggl+v89ly2/RkyPIuJlmZRdGs6ZRtK3zkk="
  [mod."github.com/prometheus/common"]
    version = "v0.34.0"
    hash = "sha256-M+v+7DntUBmiQNzfNmG3aLLufbl0XBQOubtYoNTzJDA="
  [mod."github.com/prometheus/procfs"]
    version = "v0.7.3"
    hash = "sha256-ik0WpnpSjMwifPYfQTfu/eb5ilNj+eLJF0d5Dftp8A8="
  [mod."github.com/skip2/go-qrcode"]
    version = "v0.0.0-20200617195104-da1b6568686e"
    hash = "sha256-ST9t4/b7WFXUb8wra4ZYVDNZJGrEykw8dkWhLrxp8F0="
  [mod."github.com/tidwall/gjson"]
    version = "v1.14.1"
    hash = "sha256-v8zb6n6ReFE9hmiwT7tu4avTgLCrelD9lDMMg2My/AI="
  [mod."github.com/tidwall/match"]
    version = "v1.1.1"
    hash = "sha256-M2klhPId3Q3T3VGkSbOkYl/2nLHnsG+yMbXkPkyrRdg="
  [mod."github.com/tidwall/pretty"]
    version = "v1.2.0"
    hash = "sha256-esRQGsn2Ee/CiySlwyuOICSLdqUkH4P7u8qXszos8Yc="
  [mod."github.com/tidwall/sjson"]
    version = "v1.2.4"
    hash = "sha256-Y26Yf4u/GitvqI75f5oucCew6sQjxjRNo77ab58ofVw="
  [mod."github.com/yuin/goldmark"]
    version = "v1.4.12"
    hash = "sha256-x32PnjUc9H2k7ZVP5v+/NWsjWXuGy/Ycse2ERtokq6k="
  [mod."go.mau.fi/libsignal"]
    version = "v0.0.0-20220628090436-4d18b66b087e"
    hash = "sha256-H601DPysjRRWn12zM1NRozGCkLkWriR/VviVPfpd5vY="
  [mod."go.mau.fi/whatsmeow"]
    version = "v0.0.0-20220804175245-31c5af44cb82"
    hash = "sha256-KHBIXfojUBphlwR6LaaxQpJfVuNq8Bfg++xTxTpZO+A="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20220622213112-05595931fe9d"
    hash = "sha256-2c4wvwiQ0DJSJsApfmNoxCxx1siRCiJvW9hhrGlcvds="
  [mod."golang.org/x/image"]
    version = "v0.0.0-20220617043117-41969df76e82"
    hash = "sha256-mvvoOvDLx0CSNtSTG/HO37UvVF0hX6D9CEAxgtbs9Pw="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20220624214902-1bab6f366d9e"
    hash = "sha256-LKDxEsF5v+SorAzHZGCjcY5dnpZMixI54NqapJy5jtY="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20220520151302-bc2c85ada10a"
    hash = "sha256-3xm4LbLhZjjeb8scaNFRa9zYb8z2fZj+/JBcoyXGPR8="
  [mod."golang.org/x/text"]
    version = "v0.3.7"
    hash = "sha256-XH2pUzzQx95O0rak00grQvfACfL+EmZiV7ZzJBkX+XY="
  [mod."google.golang.org/protobuf"]
    version = "v1.28.0"
    hash = "sha256-p1cVM3OeEErh1WeNRAg4n3zYm/0qPTPmIiWNjRmJiMQ="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."maunium.net/go/mauflag"]
    version = "v1.0.0"
    hash = "sha256-fYc/WwqE0ev0dvnu5qGmHJsYiSTuWeOTiAVzmQIKWyY="
  [mod."maunium.net/go/maulogger/v2"]
    version = "v2.3.2"
    hash = "sha256-FlrO1bogPrIzzVzDtIovYyr+1mNk0YaO5hEVv5zovM8="
  [mod."maunium.net/go/mautrix"]
    version = "v0.11.1-0.20220804164655-0cd3fcce0ca1"
    hash = "sha256-KSwjs4UjTGwVLoyXlQuA6a2Ddq2vvz7kzRO6BraAmmw="
