schema = 3

[mod]
  [mod."github.com/ReneKroon/ttlcache/v2"]
    version = "v2.8.1"
    hash = "sha256-Qn8ARU4j35e8CUBa9OwW2xHM7ERKuorJP+9F/thjrt4="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/cenkalti/backoff/v4"]
    version = "v4.2.1"
    hash = "sha256-CKogmPe0pCcAdpztzPwr24rLTJZfq8QVZ9AUduwAcoA="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.2.0"
    hash = "sha256-nPufwYQfTkyrEkbBrpqM3C2vnMxfIz6tAaBmiUP7vd4="
  [mod."github.com/felixge/httpsnoop"]
    version = "v1.0.3"
    hash = "sha256-qV3UPYKKBQDTzAUzzsTpfdbGhFnkmTO/r5ylPL1SyfA="
  [mod."github.com/fxamacker/cbor/v2"]
    version = "v2.5.0"
    hash = "sha256-2rhvuNZjeidDP+Og6Q0u4ROiaPrEOjoI5wCb17XRnOQ="
  [mod."github.com/getsentry/sentry-go"]
    version = "v0.20.0"
    hash = "sha256-0XH/G7GeYOyAr6KP2u5uTCAoxYvcFY1043CmDaycDwE="
  [mod."github.com/go-logr/logr"]
    version = "v1.2.4"
    hash = "sha256-+FhzmqKsAnsra5p8LuxENXJBHSeuWjQG8Tzhpyd/ps4="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/go-logr/zerologr"]
    version = "v1.2.3"
    hash = "sha256-8iBqqOlzJiTYElReCbB+2CZXn8szxH58yazHwontsJU="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.3"
    hash = "sha256-svogITcP4orUIsJFjMtp+Uv1+fKJv2Q5Zwf2dMqnpOQ="
  [mod."github.com/gorilla/mux"]
    version = "v1.8.0"
    hash = "sha256-s905hpzMH9bOLue09E2JmzPXfIS4HhAlgT7g13HCwKE="
  [mod."github.com/grpc-ecosystem/grpc-gateway/v2"]
    version = "v2.17.0"
    hash = "sha256-EZTOzai8AoC4pTh3V4KcLbsGR+1b6U0WltkrZZA0YKg="
  [mod."github.com/jmoiron/sqlx"]
    version = "v1.3.3"
    hash = "sha256-bhpbvoyhgRME1EMQFBWR0vl/wWfuk4ZuKmELH9Sox/M="
  [mod."github.com/lib/pq"]
    version = "v1.10.9"
    hash = "sha256-Gl6dLtL+yk6UrTTWfas43aM4lP/pNa2l7+ITXnjQyKs="
  [mod."github.com/matrix-org/gomatrix"]
    version = "v0.0.0-20210324163249-be2af5ef2e16"
    hash = "sha256-WS9vp/b8nJSqE0U4M1OHR1LdGsraS5KtQcVAdDfZ7UU="
  [mod."github.com/matrix-org/gomatrixserverlib"]
    version = "v0.0.0-20230105074811-965b10ae73ab"
    hash = "sha256-dUg80Mk4S5eLNpZYgN4kSCowzO96X2zWGQDZEqJTHV0="
  [mod."github.com/matrix-org/util"]
    version = "v0.0.0-20200807132607-55161520e1d4"
    hash = "sha256-LvuzVBtlgFlqIvAyred2druEijgWRLND+LXzYCxy9sA="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.19"
    hash = "sha256-wYQqGxeqV3Elkmn26Md8mKZ/viw598R4Ych3vtt72YE="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.1"
    hash = "sha256-ystDNStxR90j4CK+AMcEQ5oyYFRgWoGdvWlS0XQMDLQ="
  [mod."github.com/pressly/goose/v3"]
    version = "v3.14.0"
    hash = "sha256-BoTCzWcRd3DJQmhY+6j48bguPxIrohOTM0M+yhxpdbs="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.13.0"
    hash = "sha256-5nC5FuGuAB71k6Dm4vBcmpPpBAKfvArO/yr7e9rfQfg="
  [mod."github.com/prometheus/client_model"]
    version = "v0.2.0"
    hash = "sha256-LTHxYPRgoggl+v89ly2/RkyPIuJlmZRdGs6ZRtK3zkk="
  [mod."github.com/prometheus/common"]
    version = "v0.37.0"
    hash = "sha256-B2v0WsP8uKWYBpZcrog/sQXStIXwWZcVLmfPgnh1ZZA="
  [mod."github.com/prometheus/procfs"]
    version = "v0.11.0"
    hash = "sha256-dfbKDyKmL+BNGVuvEZmw1CiGBiwqUADxJKkIi1Sbv1Y="
  [mod."github.com/rs/xid"]
    version = "v1.4.0"
    hash = "sha256-X7WH1cxWBof4m8ZWCnP0VYQdwzBti2eoa/sqm3BmLcg="
  [mod."github.com/rs/zerolog"]
    version = "v1.29.0"
    hash = "sha256-CVRSKk2O0nwAbu0fVY/JXpKaubJHhy9gtnSbEykPO3k="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.9.3"
    hash = "sha256-EnxsWdEUPYid+aZ9H4/iMTs1XMvCLbXZRDyvj89Ebms="
  [mod."github.com/tidwall/gjson"]
    version = "v1.14.3"
    hash = "sha256-CjsKkesYwKl6hwHXB/+mvkuzW2ihKecUyvUFHUtylcw="
  [mod."github.com/tidwall/match"]
    version = "v1.1.1"
    hash = "sha256-M2klhPId3Q3T3VGkSbOkYl/2nLHnsG+yMbXkPkyrRdg="
  [mod."github.com/tidwall/pretty"]
    version = "v1.2.0"
    hash = "sha256-esRQGsn2Ee/CiySlwyuOICSLdqUkH4P7u8qXszos8Yc="
  [mod."github.com/tidwall/sjson"]
    version = "v1.2.5"
    hash = "sha256-OYGNolkmL7E1Qs2qrQ3IVpQp5gkcHNU/AB/z2O+Myps="
  [mod."github.com/x448/float16"]
    version = "v0.8.4"
    hash = "sha256-VKzMTMS9pIB/cwe17xPftCSK9Mf4Y6EuBEJlB4by5mE="
  [mod."go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"]
    version = "v0.42.0"
    hash = "sha256-LZtMXjs1bBPtB9iEkkDx3b5B2gkMkzo9X3flQz3slmM="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.16.0"
    hash = "sha256-tOn85qd55FoyzM6v162t15L0Kkxb0pzyOaCh/2HaVcE="
  [mod."go.opentelemetry.io/otel/exporters/jaeger"]
    version = "v1.16.0"
    hash = "sha256-l0R7iGb8jc6gWZOdwZS/i4zdvbstyUrERIEhQ6RIM48="
  [mod."go.opentelemetry.io/otel/exporters/otlp/internal/retry"]
    version = "v1.16.0"
    hash = "sha256-gy5ay8amiShRZhfemxxYKekzof0OSK5tRrKjFkTnwHs="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace"]
    version = "v1.16.0"
    hash = "sha256-nYF/Nv7EJruQaXbDsbLOzHVk/ji/NUaE8gMB3TZAP+c="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp"]
    version = "v1.16.0"
    hash = "sha256-IVDvM0YqxzrKaRyB393ohVrzcnF1lK6JBbnVQ0AwOWA="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.16.0"
    hash = "sha256-wl64wdxrQlHnXOK8HpPoH4xUE59DJ4nrAO2/yuzmgD0="
  [mod."go.opentelemetry.io/otel/sdk"]
    version = "v1.16.0"
    hash = "sha256-EPdo5t2OK6XBAcsV92RRXTU8CbbEdO9wcfG3oAPfki4="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.16.0"
    hash = "sha256-14YQtLnMYjjt1AlAg1CTQmQflZ+IAp48kqQghZKDXn8="
  [mod."go.opentelemetry.io/proto/otlp"]
    version = "v1.0.0"
    hash = "sha256-w2WbhXXshdm/ZmZkg5VpWwXFLjJRBBwSObyHGjJcELQ="
  [mod."golang.org/x/crypto"]
    version = "v0.12.0"
    hash = "sha256-Wes72EA9ICTG8o0nEYWZk9xjpqlniorFeY6o26GExns="
  [mod."golang.org/x/net"]
    version = "v0.14.0"
    hash = "sha256-QScKgO7lBWOsd0Y31wLRzFETv3tjqdB/eRQWW5q7aV4="
  [mod."golang.org/x/sync"]
    version = "v0.2.0"
    hash = "sha256-hKk9zsy2aXY7R0qGFZhGOVvk5qD17f6KHEuK4rGpTsg="
  [mod."golang.org/x/sys"]
    version = "v0.11.0"
    hash = "sha256-g/LjhABK2c/u6v7M2aAIrHvZjmx/ikGHkef86775N38="
  [mod."golang.org/x/text"]
    version = "v0.12.0"
    hash = "sha256-aNQaW3EgCK9ehpnBzIAkZX6TmiUU1S175YlJUH7P5Qg="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20230822172742-b8732ec3820d"
    hash = "sha256-qd9dJezVHNJZNMkywXapT1rsyD+lb25AU8aG8NJlhm4="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20230822172742-b8732ec3820d"
    hash = "sha256-1kP7lqQ+fKtARDzTrRNob0owX4GsUnxzOwLyBZSmHOc="
  [mod."google.golang.org/grpc"]
    version = "v1.57.0"
    hash = "sha256-hP6alxFu+pcLI4gT3idzEMYNp+DbU3P4xhkpIqGCPXg="
  [mod."google.golang.org/protobuf"]
    version = "v1.31.0"
    hash = "sha256-UdIk+xRaMfdhVICvKRk1THe3R1VU+lWD8hqoW/y8jT0="
