schema = 3

[mod]
  [mod."code.gitea.io/sdk/gitea"]
    version = "v0.15.1-0.20221016183512-2d9ee57af1e0"
    hash = "sha256-gBwU5pQ+0FpjmbF7vsUzguhiYn2KvOS3nBXnHyEIBmE="
  [mod."codeberg.org/6543/go-yaml2json"]
    version = "v1.0.0"
    hash = "sha256-R+N/ZOXbolCZiChdNytEgQEyurLYXVzwpd/MQc9OJno="
  [mod."codeberg.org/6543/xyaml"]
    version = "v1.1.0"
    hash = "sha256-4FzQXxT8RQguwdOiIcHDTJQvEin22gmv2+0Yx8mkLYA="
  [mod."github.com/Azure/go-ansiterm"]
    version = "v0.0.0-20210617225240-d185dfc1b5a1"
    hash = "sha256-rOhb0GMLPdnh1302vaxFjO20fM69hCT29hQD1F1YpPg="
  [mod."github.com/Microsoft/go-winio"]
    version = "v0.6.0"
    hash = "sha256-TQ0AvXZfuT3PDnb4p/h5zmyT8m9VPcwxlXMJuVD6ltE="
  [mod."github.com/alessio/shellescape"]
    version = "v1.4.1"
    hash = "sha256-rTWqbtC+EVz4fT2HmDWpucUTMtQyraInPYf2hlG8/pM="
  [mod."github.com/antonmedv/expr"]
    version = "v1.12.3"
    hash = "sha256-QSNcMscHtWVnQmpPGvL2Jj7YKtG/EZ9pGAO6cC+WuTk="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/bmatcuk/doublestar/v4"]
    version = "v4.6.0"
    hash = "sha256-0Azugw9q+RgQd7FR8cnpS4GpfWU9oAeLFmLOffMH5Iw="
  [mod."github.com/bytedance/sonic"]
    version = "v1.8.0"
    hash = "sha256-Y3LcMK+G0hkOdTycEOTeDuar1umagsT5ux7aVQ+MlKw="
  [mod."github.com/caddyserver/certmagic"]
    version = "v0.17.2"
    hash = "sha256-FPvR3VeoI+VdMkrkT+TUSgpnlMm85gUqlFfq8/HMo9c="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.2.0"
    hash = "sha256-nPufwYQfTkyrEkbBrpqM3C2vnMxfIz6tAaBmiUP7vd4="
  [mod."github.com/chenzhuoyu/base64x"]
    version = "v0.0.0-20221115062448-fe3a3abad311"
    hash = "sha256-xmONcYkIXgXomJYHR521Dr9F3XbbUM14bgf7KJ5FIFc="
  [mod."github.com/cpuguy83/go-md2man/v2"]
    version = "v2.0.2"
    hash = "sha256-OvWCtDsVrYzM84SMQwOXPLBxnWnMC1hDm+KiI6zm3uk="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/davidmz/go-pageant"]
    version = "v1.0.2"
    hash = "sha256-gfwm6i0ZGQhX2c0lDRe7qVXyHkhoHeemYpaj+O0aYyw="
  [mod."github.com/docker/cli"]
    version = "v20.10.23+incompatible"
    hash = "sha256-Xl0hJhG3EYx6TF/gblaA/tHijV/nRSkncPQ77utkXmg="
  [mod."github.com/docker/distribution"]
    version = "v2.8.1+incompatible"
    hash = "sha256-xB+w8Uaz8T6jb2LOJU5XAoMHFg/YQd3MfDFOUNKlMxE="
  [mod."github.com/docker/docker"]
    version = "v20.10.23+incompatible"
    hash = "sha256-51tBk90lsvJai5KjI08eZfpzyT8VVdk4BDeWJJxOOjI="
  [mod."github.com/docker/docker-credential-helpers"]
    version = "v0.7.0"
    hash = "sha256-Np+esoutU1psMWB0G1ayKwaWVn/XemIXxlVlooXphzg="
  [mod."github.com/docker/go-connections"]
    version = "v0.4.0"
    hash = "sha256-GHNIjOuuNp5lFQ308+nDNwQPGESCVV7bCUxSW5ZxZlc="
  [mod."github.com/docker/go-units"]
    version = "v0.5.0"
    hash = "sha256-iK/V/jJc+borzqMeqLY+38Qcts2KhywpsTk95++hImE="
  [mod."github.com/drone/envsubst"]
    version = "v1.0.3"
    hash = "sha256-U5wi+PAdrawE1RafI1Cf6mQ5Br68xFQtgBO9b6uivpo="
  [mod."github.com/emicklei/go-restful/v3"]
    version = "v3.9.0"
    hash = "sha256-qt0M3tryKAzQS4JbmTr/N5+47Ue63U0dpbWov2Me5Os="
  [mod."github.com/fatih/color"]
    version = "v1.13.0"
    hash = "sha256-Xo0zFKLm/9NuChdHDhHoUFo8Oa7Mkb3ezZCu23SfOAk="
  [mod."github.com/franela/goblin"]
    version = "v0.0.0-20211003143422-0a4f594942bf"
    hash = "sha256-ZYGrEKEROa1UrqscdI407z9MnDToU+yuUr2iyRG3rRo="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.6.0"
    hash = "sha256-DQesOCweQPEwmAn6s7DCP/Dwy8IypC+osbpfsvpkdP0="
  [mod."github.com/gin-contrib/sse"]
    version = "v0.1.0"
    hash = "sha256-zYbMTao+1F+385Lvsba9roLmmt9eYqr57sUWo0LCVhw="
  [mod."github.com/gin-gonic/gin"]
    version = "v1.9.0"
    hash = "sha256-vLkfoIeChmCKcLxRfp080tO0/2n6QBoCLxlFdUEEv+s="
  [mod."github.com/go-ap/httpsig"]
    version = "v0.0.0-20221203064646-3647b4d88fdf"
    hash = "sha256-jeMZxW+El9W4jRKvo0HkTiKD40iebY19FQMfjPq8Tdg="
  [mod."github.com/go-fed/httpsig"]
    version = "v1.1.0"
    hash = "sha256-ok0PEEvSR010nh6vB3nDCyKSSVvoB50/UjVvBKOYXsA="
  [mod."github.com/go-logr/logr"]
    version = "v1.2.3"
    hash = "sha256-2L7k6GfrcW3GXXYr1FYIu20aZBjIF0cTKdte6D4riH8="
  [mod."github.com/go-openapi/jsonpointer"]
    version = "v0.19.5"
    hash = "sha256-rLyvUdTMeQGeWiVsz2ZeyyFjHomeqd0x+ZR77mxi8Ss="
  [mod."github.com/go-openapi/jsonreference"]
    version = "v0.20.0"
    hash = "sha256-I9LAFczrUZC5MIznr/SqY0RdnQFEkAp1MJbz7h1EnGk="
  [mod."github.com/go-openapi/swag"]
    version = "v0.22.3"
    hash = "sha256-iUGFBMt9RobFG+Qsy2zKWEjFARi2xCSCaV2HRDL0vw4="
  [mod."github.com/go-playground/locales"]
    version = "v0.14.1"
    hash = "sha256-BMJGAexq96waZn60DJXZfByRHb8zA/JP/i6f/YrW9oQ="
  [mod."github.com/go-playground/universal-translator"]
    version = "v0.18.1"
    hash = "sha256-2/B2qP51zfiY+k8G0w0D03KXUc7XpWj6wKY7NjNP/9E="
  [mod."github.com/go-playground/validator/v10"]
    version = "v10.11.2"
    hash = "sha256-0mKf4ybFK/ZWoIUbmMXB3Fo9AoIqT5zAP30ce4TsBns="
  [mod."github.com/go-sql-driver/mysql"]
    version = "v1.7.0"
    hash = "sha256-xcCINvN+wEiLLmp9ltfLbDEs+/TidoBCQLODw3lMyzE="
  [mod."github.com/goccy/go-json"]
    version = "v0.10.0"
    hash = "sha256-+m829gnYn/nS0FdWyzrgmAe8a3Q7G0sriZvgwQINHF8="
  [mod."github.com/gogits/go-gogs-client"]
    version = "v0.0.0-20210131175652-1d7215cd8d85"
    hash = "sha256-FAEzj45fuhDjxiEOqgEFWtLfuZcnid7k+cAkTxuvaIU="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.2"
    hash = "sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c="
  [mod."github.com/golang-jwt/jwt/v4"]
    version = "v4.5.0"
    hash = "sha256-dyKL8wQRApkdCkKxJ1knllvixsrBLw+BtRS0SjlN7NQ="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.3"
    hash = "sha256-svogITcP4orUIsJFjMtp+Uv1+fKJv2Q5Zwf2dMqnpOQ="
  [mod."github.com/golang/snappy"]
    version = "v0.0.4"
    hash = "sha256-Umx+5xHAQCN/Gi4HbtMhnDCSPFAXSsjVbXd8n5LhjAA="
  [mod."github.com/google/gnostic"]
    version = "v0.6.9"
    hash = "sha256-kFE3mdJjOC9Wr/6/C6MMtx7j1V0ALS6oDjLaVSjN1wY="
  [mod."github.com/google/go-cmp"]
    version = "v0.5.9"
    hash = "sha256-lQc4O00R3QSMGs9LP8Sy7A9kj0cqV5rrUdpnGeipIyg="
  [mod."github.com/google/go-github/v39"]
    version = "v39.2.0"
    hash = "sha256-rzMQo5Cnmky9zehUDaGrG2nL25hAd55jJe/efay04CM="
  [mod."github.com/google/go-querystring"]
    version = "v1.1.0"
    hash = "sha256-itsKgKghuX26czU79cK6C2n+lc27jm5Dw1XbIRgwZJY="
  [mod."github.com/google/gofuzz"]
    version = "v1.2.0"
    hash = "sha256-T6Gz741l45L3F6Dt7fiAuQvQQg59Qtap3zG05M2cfqU="
  [mod."github.com/google/tink/go"]
    version = "v1.7.0"
    hash = "sha256-545LoMrptf9L51OvGMmINPKZAXWQHc9FdSGtSAwtQug="
  [mod."github.com/gorilla/securecookie"]
    version = "v1.1.1"
    hash = "sha256-IBBYWfdOuXvQsb01DaA8tBizCfAE1J2KLXIn3W+NeJk="
  [mod."github.com/hashicorp/go-cleanhttp"]
    version = "v0.5.2"
    hash = "sha256-N9GOKYo7tK6XQUFhvhImtL7PZW/mr4C4Manx/yPVvcQ="
  [mod."github.com/hashicorp/go-hclog"]
    version = "v1.0.0"
    hash = "sha256-rcP8GEBXklcbO7V0E/0FKke4KTXmDncc5FpxYyAujUA="
  [mod."github.com/hashicorp/go-retryablehttp"]
    version = "v0.7.2"
    hash = "sha256-PcLyolWF7G409rs7j3tnwgQK6xhgWYk9/iK2bO13TGQ="
  [mod."github.com/hashicorp/go-version"]
    version = "v1.6.0"
    hash = "sha256-UV0equpmW6BiJnp4W3TZlSJ+PTHuTA+CdOs2JTeHhjs="
  [mod."github.com/imdario/mergo"]
    version = "v0.3.13"
    hash = "sha256-03LKAZXgR5YUMeK5IRh2ds2GyV6uSbdq5QCPbAzlTus="
  [mod."github.com/joho/godotenv"]
    version = "v1.5.1"
    hash = "sha256-kA0osKfsc6Kp+nuGTRJyXZZlJt1D/kuEazKMWYCWcQ8="
  [mod."github.com/josharian/intern"]
    version = "v1.0.0"
    hash = "sha256-LJR0QE2vOQ2/2shBbO5Yl8cVPq+NFrE3ers0vu9FRP0="
  [mod."github.com/json-iterator/go"]
    version = "v1.1.12"
    hash = "sha256-To8A0h+lbfZ/6zM+2PpRpY3+L6725OPC66lffq6fUoM="
  [mod."github.com/klauspost/cpuid/v2"]
    version = "v2.1.2"
    hash = "sha256-Qm5gCgbGcM5Pp6Xy/T+uWqbJbZLnZqLszw1tjuj2aK4="
  [mod."github.com/kr/fs"]
    version = "v0.1.0"
    hash = "sha256-+Cjz0rGmdNIV1QL4z8h7JAjHATa5pKndwSnD1M0J74c="
  [mod."github.com/lafriks/ttlcache/v3"]
    version = "v3.2.0"
    hash = "sha256-4X/8FCy5CxZlByUHMJlMc9v8KBhaxNsH8ivQmPQbiSA="
  [mod."github.com/leodido/go-urn"]
    version = "v1.2.1"
    hash = "sha256-02UfyUwMtTGMUYJOEmiJYOc3LXumr+f7pCT3J7h7iFg="
  [mod."github.com/lib/pq"]
    version = "v1.10.7"
    hash = "sha256-YPUv1VBZNFVUjFxQKdYd0Djje6KYYE99Hz6FnTfrmMw="
  [mod."github.com/libdns/libdns"]
    version = "v0.2.1"
    hash = "sha256-bxEY0wYu4Um0t7sakLyMwMPDXfv2x07gjckKSyAypsc="
  [mod."github.com/mailru/easyjson"]
    version = "v0.7.7"
    hash = "sha256-NVCz8MURpxgOjHXqxOZExqV4bnpHggpeAOyZDArjcy4="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.17"
    hash = "sha256-c1u9eiMF9wLXgGvPTB5DH6S8uuCPqWZJTa6tCGuB3Ek="
  [mod."github.com/mattn/go-sqlite3"]
    version = "v1.14.16"
    hash = "sha256-Ky0kas72AY0lpuRiC/fQk9rw9aJ6dvL9y1Ikw5PFzlA="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.2"
    hash = "sha256-uovu7OycdeZ2oYQ7FhVxLey5ZX3T0FzShaRldndyGvc="
  [mod."github.com/melbahja/goph"]
    version = "v1.3.1"
    hash = "sha256-7KPWzkvXT/rnR0GoH3NDnuSvterKmLhrA0BTb+gH3OM="
  [mod."github.com/mholt/acmez"]
    version = "v1.0.4"
    hash = "sha256-HXGdY4WtS5V70hWRScTzQdc/3OY5gp5aRzCfIfWIqVo="
  [mod."github.com/miekg/dns"]
    version = "v1.1.50"
    hash = "sha256-mtf3QAk46pCA0a1K+oH6a7oqsY6LR6Qr8HD4qnDqe+s="
  [mod."github.com/moby/moby"]
    version = "v20.10.23+incompatible"
    hash = "sha256-51tBk90lsvJai5KjI08eZfpzyT8VVdk4BDeWJJxOOjI="
  [mod."github.com/moby/term"]
    version = "v0.0.0-20221205130635-1aeaba878587"
    hash = "sha256-wX2ftzjEHzltzN68CsYVXMiaLPNU7V2phVyyPKv3mn8="
  [mod."github.com/modern-go/concurrent"]
    version = "v0.0.0-20180306012644-bacd9c7ef1dd"
    hash = "sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo="
  [mod."github.com/modern-go/reflect2"]
    version = "v1.0.2"
    hash = "sha256-+W9EIW7okXIXjWEgOaMh58eLvBZ7OshW2EhaIpNLSBU="
  [mod."github.com/morikuni/aec"]
    version = "v1.0.0"
    hash = "sha256-5zYgLeGr3K+uhGKlN3xv0PO67V+2Zw+cezjzNCmAWOE="
  [mod."github.com/mrjones/oauth"]
    version = "v0.0.0-20190623134757-126b35219450"
    hash = "sha256-nHhQ8lhmPOx+vZBpWAHx0ddD7aDfAUYNF/yhVbOPmKU="
  [mod."github.com/munnerz/goautoneg"]
    version = "v0.0.0-20191010083416-a7dc8b61c822"
    hash = "sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q="
  [mod."github.com/oklog/ulid/v2"]
    version = "v2.1.0"
    hash = "sha256-/oQPgcO1xKbHXutxz0WPfIduShPrfH1l+7/mj8jLst8="
  [mod."github.com/onsi/ginkgo"]
    version = "v1.16.4"
    hash = "sha256-+rsbCrlS+05k+G14Ov/GYAmpLN09Vp0F2LMKkyUIftE="
  [mod."github.com/opencontainers/go-digest"]
    version = "v1.0.0"
    hash = "sha256-cfVDjHyWItmUGZ2dzQhCHgmOmou8v7N+itDkLZVkqkQ="
  [mod."github.com/opencontainers/image-spec"]
    version = "v1.1.0-rc2"
    hash = "sha256-833S8D86IumLRpfrKBzpZCtLsTEnGBWbI3dTYd6BdFg="
  [mod."github.com/pelletier/go-toml/v2"]
    version = "v2.0.6"
    hash = "sha256-BxAeApnn5H+OLlH3TXGvIbtC6LmbRnjwbcfT1qMZ4PE="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pkg/sftp"]
    version = "v1.13.5"
    hash = "sha256-z5AbvM8kGlpF1LQy0pQpij7KMR5bE+1HppvamBRt8F4="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.14.0"
    hash = "sha256-dpgGV8C30ZCn7b9mQ+Ye2AfPXTIuHLQbl2olMKzJKxA="
  [mod."github.com/prometheus/client_model"]
    version = "v0.3.0"
    hash = "sha256-vP+miJfsoK5UG9eug8z/bhAMj3bwg66T2vIh8WHoOKU="
  [mod."github.com/prometheus/common"]
    version = "v0.37.0"
    hash = "sha256-B2v0WsP8uKWYBpZcrog/sQXStIXwWZcVLmfPgnh1ZZA="
  [mod."github.com/prometheus/procfs"]
    version = "v0.8.0"
    hash = "sha256-hgrilokQsXCOCCvwgOSfuErxoFAQpXM/+zNJKcMVHyM="
  [mod."github.com/robfig/cron"]
    version = "v1.2.0"
    hash = "sha256-au+MD6DEjpVRAjXWmmJbZRB5IdFfcIqGm6kBkkYNY1s="
  [mod."github.com/rogpeppe/go-internal"]
    version = "v1.8.1"
    hash = "sha256-kXGiB1aTKIfgCKhZvSfIOyTL09EvMhzQEyhRmUhe7Ho="
  [mod."github.com/rs/zerolog"]
    version = "v1.29.0"
    hash = "sha256-CVRSKk2O0nwAbu0fVY/JXpKaubJHhy9gtnSbEykPO3k="
  [mod."github.com/russross/blackfriday/v2"]
    version = "v2.1.0"
    hash = "sha256-R+84l1si8az5yDqd5CYcFrTyNZ1eSYlpXKq6nFt4OTQ="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.9.0"
    hash = "sha256-xOwGFsYGIxNiurS8Zue8mhlFK/G7U1LVFFrv4vcr1GM="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/stretchr/objx"]
    version = "v0.5.0"
    hash = "sha256-nY4mvP0f0Ry1IKMKQAYNuioA5h4red4mmQqeGZw6EF0="
  [mod."github.com/stretchr/testify"]
    version = "v1.8.2"
    hash = "sha256-n32PGyJL6VLtwOGEbS0lFchxunNU9nlol7OSEZlrKUM="
  [mod."github.com/syndtr/goleveldb"]
    version = "v1.0.0"
    hash = "sha256-rW7SW6nehede0oMZo4NBatM6Eizbnlb7xYoX/dcDUxA="
  [mod."github.com/tevino/abool"]
    version = "v1.2.0"
    hash = "sha256-rmsOhWdU9huKJd0YEvxo4gZhCgZgUy5slFAhYvAXvXA="
  [mod."github.com/twitchyliquid64/golang-asm"]
    version = "v0.15.1"
    hash = "sha256-HLk6oUe7EoITrNvP0y8D6BtIgIcmDZYtb/xl/dufIoY="
  [mod."github.com/ugorji/go/codec"]
    version = "v1.2.9"
    hash = "sha256-LUyCclmjVNbf6iiztNOrEsKzrwmG3mpmM1ykzh/BQ/s="
  [mod."github.com/urfave/cli/v2"]
    version = "v2.25.0"
    hash = "sha256-3XQyFJiErN2b6XRNIsYOEfFPTVh6ro13UNJqqq+zqqs="
  [mod."github.com/xanzy/go-gitlab"]
    version = "v0.81.0"
    hash = "sha256-u2iicw5GtiaHGUdbQWDf27UDjfOjF/vFYgF9lxx4SBc="
  [mod."github.com/xeipuuv/gojsonpointer"]
    version = "v0.0.0-20190905194746-02993c407bfb"
    hash = "sha256-/u+qznDY8cnECZYIgSMRpKVWs04yAkW6EoGhqt+t73g="
  [mod."github.com/xeipuuv/gojsonreference"]
    version = "v0.0.0-20180127040603-bd5ef7bd5415"
    hash = "sha256-ZbXA+ASQrTgBQzasUKC9vznrOGpquYyWr+uwpm46fvU="
  [mod."github.com/xeipuuv/gojsonschema"]
    version = "v1.2.0"
    hash = "sha256-1ERBEvxj3pvHkMS2mvmvmYRi8jgAaTquo5hwjDLAEdc="
  [mod."github.com/xrash/smetrics"]
    version = "v0.0.0-20201216005158-039620a65673"
    hash = "sha256-WGHtW/OkLowkqOYIvXpDOpn9wqdH2+Dyx3+rYwpmvzI="
  [mod."go.uber.org/atomic"]
    version = "v1.10.0"
    hash = "sha256-E6UEDc1eh/cLUFd+J86cDesQ0B8wEv/DdaAVKb+x2t8="
  [mod."go.uber.org/multierr"]
    version = "v1.6.0"
    hash = "sha256-X+l7OPAkMhpw+5VvFWuQ/DfTCSjQH/8VvSoQrb44CEU="
  [mod."go.uber.org/zap"]
    version = "v1.23.0"
    hash = "sha256-A/Wf2F9yc+OTyX86QjTtzemUOaFSd7ptoNFaqr2smig="
  [mod."golang.org/x/arch"]
    version = "v0.0.0-20210923205945-b76863e36670"
    hash = "sha256-GRRcSkvNi5Cf9q3UkNVux5yy8n5mPQIFofv1fSSYqQ0="
  [mod."golang.org/x/crypto"]
    version = "v0.7.0"
    hash = "sha256-Yc4casCQyfOgIr48FV+NI9qhanhBuYnkph5iI7rDyZE="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20230315142452-642cacee5cc0"
    hash = "sha256-EIbPHNoqK3ObKd8eLBU6i1Pr1XNmkRy+rEHgPf1s814="
  [mod."golang.org/x/mod"]
    version = "v0.8.0"
    hash = "sha256-cgtmxQA937+MdXUiPrVeDvRoqhxD4hvIbtXAjK2SM8U="
  [mod."golang.org/x/net"]
    version = "v0.8.0"
    hash = "sha256-2cOtqa7aJ5mn64kZ+8+PVjJ4uGbhpXTpC1vm/+iaZzM="
  [mod."golang.org/x/oauth2"]
    version = "v0.6.0"
    hash = "sha256-M6yqSRqMcgp4bOCa4ey8/13z/0BrjQgyUQXJZU1hmnw="
  [mod."golang.org/x/sync"]
    version = "v0.1.0"
    hash = "sha256-Hygjq9euZ0qz6TvHYQwOZEjNiTbTh1nSLRAWZ6KFGR8="
  [mod."golang.org/x/sys"]
    version = "v0.6.0"
    hash = "sha256-zAgxiTuL24sGhbXrna9R1UYqLQh46ldztpumOScmduY="
  [mod."golang.org/x/term"]
    version = "v0.6.0"
    hash = "sha256-Ao0yXpwY8GyG+/23dVfJUYrfEfNUTES3RF45v1VhUAk="
  [mod."golang.org/x/text"]
    version = "v0.8.0"
    hash = "sha256-hgWFnT01DRmywBEXKYEVaOee7i6z8Ydz7zGbjcWwOgI="
  [mod."golang.org/x/time"]
    version = "v0.3.0"
    hash = "sha256-/hmc9skIswMYbivxNS7R8A6vCTUF9k2/7tr/ACkcEaM="
  [mod."golang.org/x/tools"]
    version = "v0.6.0"
    hash = "sha256-J0q+C3WDTK9yyHX90FV6qr6n9H07YglYg1p4H3MqyH4="
  [mod."google.golang.org/appengine"]
    version = "v1.6.7"
    hash = "sha256-zIxGRHiq4QBvRqkrhMGMGCaVL4iM4TtlYpAi/hrivS4="
  [mod."google.golang.org/genproto"]
    version = "v0.0.0-20230110181048-76db0878b65f"
    hash = "sha256-Jc90F9KU+ZKI0ynF/p3Vwl7TJPb7/MxDFs0ebagty2s="
  [mod."google.golang.org/grpc"]
    version = "v1.53.0"
    hash = "sha256-LkB13k1JaQ7e4nGpCoEA9q4T8oIV0KvkFIDZmHhDr08="
  [mod."google.golang.org/protobuf"]
    version = "v1.30.0"
    hash = "sha256-Y07NKhSuJQ2w7F7MAINQyBf+/hdMHOrxwA3B4ljQQKs="
  [mod."gopkg.in/inf.v0"]
    version = "v0.9.1"
    hash = "sha256-z84XlyeWLcoYOvWLxPkPFgLkpjyb2Y4pdeGMyySOZQI="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."gotest.tools/v3"]
    version = "v3.0.3"
    hash = "sha256-i85wfMtfsGEtNOb97u0AOKC7olBpwf6EURP9IWoY2yg="
  [mod."k8s.io/api"]
    version = "v0.26.3"
    hash = "sha256-youX6CPK+qKf8LC1SiqdxGY7EPygnYAn1/0DKddILhg="
  [mod."k8s.io/apimachinery"]
    version = "v0.26.3"
    hash = "sha256-yWnEgX5MW+geftt/uH5Fp+0lRiZ1uIsQDs25UBf84z4="
  [mod."k8s.io/client-go"]
    version = "v0.26.3"
    hash = "sha256-OVb3DBsnnLoH1E9gIO8/MGxQuDpveTeJvr9GodERC10="
  [mod."k8s.io/klog/v2"]
    version = "v2.80.1"
    hash = "sha256-2x5xerTWGlkutsiqOsIyvTG7k0NSfcZqhgDLSmtbxGU="
  [mod."k8s.io/kube-openapi"]
    version = "v0.0.0-20221012153701-172d655c2280"
    hash = "sha256-WoBpg3hcwOlGmH8CVQp9f8DS9IA5sUJEbMd4p1R35bc="
  [mod."k8s.io/utils"]
    version = "v0.0.0-20221107191617-1a15be271d1d"
    hash = "sha256-9KGF7en1Ah+hYeGDfmlzYVgQPKXIPEK9BKCVRFiHF54="
  [mod."sigs.k8s.io/json"]
    version = "v0.0.0-20220713155537-f223a00ba0e2"
    hash = "sha256-hWhSoc0Y7YbWfUbesf0tOgEPK61F/tNQo2zN6RcYgro="
  [mod."sigs.k8s.io/structured-merge-diff/v4"]
    version = "v4.2.3"
    hash = "sha256-v6u6ZqnrEeQ2c7BYkltPKuBFL7+939OT1EbWw0mUE7U="
  [mod."sigs.k8s.io/yaml"]
    version = "v1.3.0"
    hash = "sha256-RVp8vca2wxg8pcBDYospG7Z1dujoH7zXNu2rgZ1kky0="
  [mod."xorm.io/builder"]
    version = "v0.3.12"
    hash = "sha256-Hgn8gSBNkXpF9vxuXy+j+dfj8ZbYrYldg2vkqwcSSCA="
  [mod."xorm.io/xorm"]
    version = "v1.3.2"
    hash = "sha256-aGqY8LchffNR6SvEbd4yXJY0I37+MlbyK+l6RZRRHM0="
