schema = 3

[mod]
  [mod."code.gitea.io/sdk/gitea"]
    version = "v0.16.0"
    hash = "sha256-KU+2V5zGARWR4GakAmXkl8JYPrtxXkjOKmAELePrcFI="
  [mod."codeberg.org/6543/go-yaml2json"]
    version = "v1.0.0"
    hash = "sha256-R+N/ZOXbolCZiChdNytEgQEyurLYXVzwpd/MQc9OJno="
  [mod."codeberg.org/6543/xyaml"]
    version = "v1.1.0"
    hash = "sha256-4FzQXxT8RQguwdOiIcHDTJQvEin22gmv2+0Yx8mkLYA="
  [mod."github.com/6543/logfile-open"]
    version = "v1.2.1"
    hash = "sha256-HiX2GwYubPJklfaKB05uOV9+sB7TgO+4lJoTlAMoX7U="
  [mod."github.com/Azure/go-ansiterm"]
    version = "v0.0.0-20210617225240-d185dfc1b5a1"
    hash = "sha256-rOhb0GMLPdnh1302vaxFjO20fM69hCT29hQD1F1YpPg="
  [mod."github.com/KyleBanks/depth"]
    version = "v1.2.1"
    hash = "sha256-czR52MfeKA2FdStXCebTMQRKT8jaWQcbV214O3j49qU="
  [mod."github.com/Microsoft/go-winio"]
    version = "v0.6.1"
    hash = "sha256-BL0BVaHtmPKQts/711W59AbHXjGKqFS4ZTal0RYnR9I="
  [mod."github.com/ProtonMail/go-crypto"]
    version = "v0.0.0-20230217124315-7d5c6f04bbb8"
    hash = "sha256-QWS55wWNCrgx6BbIrroWpc1s08FeSqf2ehNTXkhbDJQ="
  [mod."github.com/alessio/shellescape"]
    version = "v1.4.2"
    hash = "sha256-TOlNouGwNdaCddRwABb1qXp0HTMt6+G4uatzfAg3XFc="
  [mod."github.com/antonmedv/expr"]
    version = "v1.15.3"
    hash = "sha256-j6ZvAK4MgiyDnXw4TxnfjBYgxrde4P6kEYROzj10qxc="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/bmatcuk/doublestar/v4"]
    version = "v4.6.0"
    hash = "sha256-0Azugw9q+RgQd7FR8cnpS4GpfWU9oAeLFmLOffMH5Iw="
  [mod."github.com/bytedance/sonic"]
    version = "v1.9.1"
    hash = "sha256-u8fAQs/8St/jKxhnsDVh9eVZdN28S+S/hA1yqu/UQLs="
  [mod."github.com/caddyserver/certmagic"]
    version = "v0.19.2"
    hash = "sha256-ruz2oG5E834tMjyL/HdFPaWlNuwBg/fxqVitZX3sQR0="
  [mod."github.com/cenkalti/backoff/v4"]
    version = "v4.2.1"
    hash = "sha256-CKogmPe0pCcAdpztzPwr24rLTJZfq8QVZ9AUduwAcoA="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.2.0"
    hash = "sha256-nPufwYQfTkyrEkbBrpqM3C2vnMxfIz6tAaBmiUP7vd4="
  [mod."github.com/chenzhuoyu/base64x"]
    version = "v0.0.0-20221115062448-fe3a3abad311"
    hash = "sha256-xmONcYkIXgXomJYHR521Dr9F3XbbUM14bgf7KJ5FIFc="
  [mod."github.com/cloudflare/circl"]
    version = "v1.3.3"
    hash = "sha256-ItdVkU53Ep01553/tJ4MdAwoTpPljRxiBW9sAd7p0xI="
  [mod."github.com/cpuguy83/go-md2man/v2"]
    version = "v2.0.2"
    hash = "sha256-OvWCtDsVrYzM84SMQwOXPLBxnWnMC1hDm+KiI6zm3uk="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/davidmz/go-pageant"]
    version = "v1.0.2"
    hash = "sha256-gfwm6i0ZGQhX2c0lDRe7qVXyHkhoHeemYpaj+O0aYyw="
  [mod."github.com/distribution/reference"]
    version = "v0.5.0"
    hash = "sha256-nTlqurp/J/xOZeR0JcJMmE4GUHMMd5I+EOR7huzYuok="
  [mod."github.com/docker/cli"]
    version = "v20.10.26+incompatible"
    hash = "sha256-raz6w//bxBzWhTV4Ocmqkm7QyaWxF/NsKWUCcfa0T3c="
  [mod."github.com/docker/distribution"]
    version = "v2.8.3+incompatible"
    hash = "sha256-XhRURCGNpJC83QZTtgCxHHFL76HaxIxjt70HwUa847E="
  [mod."github.com/docker/docker"]
    version = "v20.10.26+incompatible"
    hash = "sha256-vECQfJ/AVSTLsXNC4r2VVK1SoIzAiqDlxIWM+lGXqYQ="
  [mod."github.com/docker/docker-credential-helpers"]
    version = "v0.7.0"
    hash = "sha256-Np+esoutU1psMWB0G1ayKwaWVn/XemIXxlVlooXphzg="
  [mod."github.com/docker/go-connections"]
    version = "v0.4.0"
    hash = "sha256-GHNIjOuuNp5lFQ308+nDNwQPGESCVV7bCUxSW5ZxZlc="
  [mod."github.com/docker/go-units"]
    version = "v0.5.0"
    hash = "sha256-iK/V/jJc+borzqMeqLY+38Qcts2KhywpsTk95++hImE="
  [mod."github.com/drone/envsubst"]
    version = "v1.0.3"
    hash = "sha256-U5wi+PAdrawE1RafI1Cf6mQ5Br68xFQtgBO9b6uivpo="
  [mod."github.com/emicklei/go-restful/v3"]
    version = "v3.9.0"
    hash = "sha256-qt0M3tryKAzQS4JbmTr/N5+47Ue63U0dpbWov2Me5Os="
  [mod."github.com/fatih/color"]
    version = "v1.13.0"
    hash = "sha256-Xo0zFKLm/9NuChdHDhHoUFo8Oa7Mkb3ezZCu23SfOAk="
  [mod."github.com/franela/goblin"]
    version = "v0.0.0-20211003143422-0a4f594942bf"
    hash = "sha256-ZYGrEKEROa1UrqscdI407z9MnDToU+yuUr2iyRG3rRo="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.6.0"
    hash = "sha256-DQesOCweQPEwmAn6s7DCP/Dwy8IypC+osbpfsvpkdP0="
  [mod."github.com/gabriel-vasile/mimetype"]
    version = "v1.4.2"
    hash = "sha256-laV+IkgbnEG07h1eFfPISqp0ctnLXfzchz/CLR1lftk="
  [mod."github.com/gin-contrib/sse"]
    version = "v0.1.0"
    hash = "sha256-zYbMTao+1F+385Lvsba9roLmmt9eYqr57sUWo0LCVhw="
  [mod."github.com/gin-gonic/gin"]
    version = "v1.9.1"
    hash = "sha256-3FHywH5QuhTeQcdF8v06jt9vIkH0ON6ydpMYciAc8xQ="
  [mod."github.com/go-ap/httpsig"]
    version = "v0.0.0-20221203064646-3647b4d88fdf"
    hash = "sha256-jeMZxW+El9W4jRKvo0HkTiKD40iebY19FQMfjPq8Tdg="
  [mod."github.com/go-fed/httpsig"]
    version = "v1.1.0"
    hash = "sha256-ok0PEEvSR010nh6vB3nDCyKSSVvoB50/UjVvBKOYXsA="
  [mod."github.com/go-logr/logr"]
    version = "v1.2.4"
    hash = "sha256-+FhzmqKsAnsra5p8LuxENXJBHSeuWjQG8Tzhpyd/ps4="
  [mod."github.com/go-openapi/jsonpointer"]
    version = "v0.19.6"
    hash = "sha256-C/ICmPQu0faBiZ/qCHoy6Nzyy2FDO5QiahzlXSCwvIw="
  [mod."github.com/go-openapi/jsonreference"]
    version = "v0.20.2"
    hash = "sha256-klWZKK7LZqSg3HMIrSkjh/NwaZTr+8kTW2ok2+JlioE="
  [mod."github.com/go-openapi/spec"]
    version = "v0.20.8"
    hash = "sha256-1hj2wZBodG0yw86vEKL9+u1LGwHRXrhRVDzvGpM8o9M="
  [mod."github.com/go-openapi/swag"]
    version = "v0.22.3"
    hash = "sha256-iUGFBMt9RobFG+Qsy2zKWEjFARi2xCSCaV2HRDL0vw4="
  [mod."github.com/go-playground/locales"]
    version = "v0.14.1"
    hash = "sha256-BMJGAexq96waZn60DJXZfByRHb8zA/JP/i6f/YrW9oQ="
  [mod."github.com/go-playground/universal-translator"]
    version = "v0.18.1"
    hash = "sha256-2/B2qP51zfiY+k8G0w0D03KXUc7XpWj6wKY7NjNP/9E="
  [mod."github.com/go-playground/validator/v10"]
    version = "v10.14.0"
    hash = "sha256-9bZ6GTH3Lr7bYLgOIurHmMOyiZna4wW6QyuEP3dHX5g="
  [mod."github.com/go-sql-driver/mysql"]
    version = "v1.7.1"
    hash = "sha256-3iKt+BKDz5FX2246Tg41weIuEDYd1YI40N6alJI9Bks="
  [mod."github.com/goccy/go-json"]
    version = "v0.10.2"
    hash = "sha256-6fMD2/Rku8HT0zDdeA23pX0YxbohiIOC8OJNYbylJTQ="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.2"
    hash = "sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c="
  [mod."github.com/golang-jwt/jwt/v5"]
    version = "v5.0.0"
    hash = "sha256-eJhOeyjkEwQAN9cwwAIU4RqnbzHmbDYW27/EzcKgj9Q="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.3"
    hash = "sha256-svogITcP4orUIsJFjMtp+Uv1+fKJv2Q5Zwf2dMqnpOQ="
  [mod."github.com/golang/snappy"]
    version = "v0.0.4"
    hash = "sha256-Umx+5xHAQCN/Gi4HbtMhnDCSPFAXSsjVbXd8n5LhjAA="
  [mod."github.com/google/gnostic-models"]
    version = "v0.6.8"
    hash = "sha256-YzA/XpvPyfdplJtHmAUdQk9P+j0NBwHhW9nj1DaGaoQ="
  [mod."github.com/google/go-cmp"]
    version = "v0.5.9"
    hash = "sha256-lQc4O00R3QSMGs9LP8Sy7A9kj0cqV5rrUdpnGeipIyg="
  [mod."github.com/google/go-github/v55"]
    version = "v55.0.0"
    hash = "sha256-+c3sCiFJ7dY0zbTr7ijlja2wpvRVCodEDikTApCXd/s="
  [mod."github.com/google/go-querystring"]
    version = "v1.1.0"
    hash = "sha256-itsKgKghuX26czU79cK6C2n+lc27jm5Dw1XbIRgwZJY="
  [mod."github.com/google/gofuzz"]
    version = "v1.2.0"
    hash = "sha256-T6Gz741l45L3F6Dt7fiAuQvQQg59Qtap3zG05M2cfqU="
  [mod."github.com/google/tink/go"]
    version = "v1.7.0"
    hash = "sha256-545LoMrptf9L51OvGMmINPKZAXWQHc9FdSGtSAwtQug="
  [mod."github.com/google/uuid"]
    version = "v1.3.1"
    hash = "sha256-JxAEAB2bFlGPShFreyOWjUahjaGV3xYS5TpfUOikod0="
  [mod."github.com/gorilla/securecookie"]
    version = "v1.1.1"
    hash = "sha256-IBBYWfdOuXvQsb01DaA8tBizCfAE1J2KLXIn3W+NeJk="
  [mod."github.com/hashicorp/go-cleanhttp"]
    version = "v0.5.2"
    hash = "sha256-N9GOKYo7tK6XQUFhvhImtL7PZW/mr4C4Manx/yPVvcQ="
  [mod."github.com/hashicorp/go-hclog"]
    version = "v1.2.0"
    hash = "sha256-XGIirpWp3lFLaBK5lHLVnNMwkVGCnnyt7Pqranb4amQ="
  [mod."github.com/hashicorp/go-retryablehttp"]
    version = "v0.7.4"
    hash = "sha256-/Gz+M2TPdVW+9zL+Oh1oC8kLrla2Uvl1S16SMH4qYRw="
  [mod."github.com/hashicorp/go-version"]
    version = "v1.5.0"
    hash = "sha256-nrV59GgQHrZ0i/pyighGahr0Or/x3jNeyS/TD67HCf4="
  [mod."github.com/imdario/mergo"]
    version = "v0.3.12"
    hash = "sha256-IPGunEznxlUilS22LUU4p/QTA7f5+Goowf1Utg9ARpc="
  [mod."github.com/jellydator/ttlcache/v3"]
    version = "v3.1.0"
    hash = "sha256-KWjdJrANQcgrRbao+PCCm2qyiBgedA5xNFxvWqqeoFQ="
  [mod."github.com/joho/godotenv"]
    version = "v1.5.1"
    hash = "sha256-kA0osKfsc6Kp+nuGTRJyXZZlJt1D/kuEazKMWYCWcQ8="
  [mod."github.com/josharian/intern"]
    version = "v1.0.0"
    hash = "sha256-LJR0QE2vOQ2/2shBbO5Yl8cVPq+NFrE3ers0vu9FRP0="
  [mod."github.com/json-iterator/go"]
    version = "v1.1.12"
    hash = "sha256-To8A0h+lbfZ/6zM+2PpRpY3+L6725OPC66lffq6fUoM="
  [mod."github.com/klauspost/cpuid/v2"]
    version = "v2.2.5"
    hash = "sha256-/M8CHNah2/EPr0va44r1Sx+3H6E+jN8bGFi5jQkLBrM="
  [mod."github.com/kr/fs"]
    version = "v0.1.0"
    hash = "sha256-+Cjz0rGmdNIV1QL4z8h7JAjHATa5pKndwSnD1M0J74c="
  [mod."github.com/leodido/go-urn"]
    version = "v1.2.4"
    hash = "sha256-N2HO7ChScxI79KGvXI9LxoIlr+lkBNdDZP9OPGwPRK0="
  [mod."github.com/lib/pq"]
    version = "v1.10.9"
    hash = "sha256-Gl6dLtL+yk6UrTTWfas43aM4lP/pNa2l7+ITXnjQyKs="
  [mod."github.com/libdns/libdns"]
    version = "v0.2.1"
    hash = "sha256-bxEY0wYu4Um0t7sakLyMwMPDXfv2x07gjckKSyAypsc="
  [mod."github.com/mailru/easyjson"]
    version = "v0.7.7"
    hash = "sha256-NVCz8MURpxgOjHXqxOZExqV4bnpHggpeAOyZDArjcy4="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.19"
    hash = "sha256-wYQqGxeqV3Elkmn26Md8mKZ/viw598R4Ych3vtt72YE="
  [mod."github.com/mattn/go-sqlite3"]
    version = "v1.14.17"
    hash = "sha256-ictf2uCW2AnQbykhI0kKPXwzHQlbHHZflZgvpqGFquY="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.4"
    hash = "sha256-uovu7OycdeZ2oYQ7FhVxLey5ZX3T0FzShaRldndyGvc="
  [mod."github.com/melbahja/goph"]
    version = "v1.4.0"
    hash = "sha256-YIrRwgacGIcBCAnIW0XwMzTBwNmrOXCpAwbqNaqx2vA="
  [mod."github.com/mholt/acmez"]
    version = "v1.2.0"
    hash = "sha256-zfj14WFQr1/AO64gYsbFk4a4T0dsMEs+W3uIa9968/M="
  [mod."github.com/miekg/dns"]
    version = "v1.1.55"
    hash = "sha256-Jbii9veDSpqF7yIkdrzb/bEUM3wZG41mNEAYV3VEAJo="
  [mod."github.com/moby/moby"]
    version = "v20.10.26+incompatible"
    hash = "sha256-vECQfJ/AVSTLsXNC4r2VVK1SoIzAiqDlxIWM+lGXqYQ="
  [mod."github.com/moby/term"]
    version = "v0.5.0"
    hash = "sha256-jy0kbkeUsr0KoiE33WLxNAgYXZIERKR2O5+saXBwdD8="
  [mod."github.com/modern-go/concurrent"]
    version = "v0.0.0-20180306012644-bacd9c7ef1dd"
    hash = "sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo="
  [mod."github.com/modern-go/reflect2"]
    version = "v1.0.2"
    hash = "sha256-+W9EIW7okXIXjWEgOaMh58eLvBZ7OshW2EhaIpNLSBU="
  [mod."github.com/morikuni/aec"]
    version = "v1.0.0"
    hash = "sha256-5zYgLeGr3K+uhGKlN3xv0PO67V+2Zw+cezjzNCmAWOE="
  [mod."github.com/munnerz/goautoneg"]
    version = "v0.0.0-20191010083416-a7dc8b61c822"
    hash = "sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q="
  [mod."github.com/oklog/ulid/v2"]
    version = "v2.1.0"
    hash = "sha256-/oQPgcO1xKbHXutxz0WPfIduShPrfH1l+7/mj8jLst8="
  [mod."github.com/opencontainers/go-digest"]
    version = "v1.0.0"
    hash = "sha256-cfVDjHyWItmUGZ2dzQhCHgmOmou8v7N+itDkLZVkqkQ="
  [mod."github.com/opencontainers/image-spec"]
    version = "v1.0.2"
    hash = "sha256-X7kZoMYZNOIDpx8ziK7V+5YM07qiYWOE4yJo+sTOjjU="
  [mod."github.com/pelletier/go-toml/v2"]
    version = "v2.0.8"
    hash = "sha256-wWxswr/lTq+McYbScmJM1ECKQ6eNJ5m44SM7TmrHThM="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pkg/sftp"]
    version = "v1.13.5"
    hash = "sha256-z5AbvM8kGlpF1LQy0pQpij7KMR5bE+1HppvamBRt8F4="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.17.0"
    hash = "sha256-FIIzCuNqHdVzpbyH7yAp7Tcu+1tPxEMS5g6KfsGQBGE="
  [mod."github.com/prometheus/client_model"]
    version = "v0.4.1-0.20230718164431-9a2bf3000d16"
    hash = "sha256-t9LgImRW4h0XMSxfAazrGHqyDljDyl0YC5r9cYuXcKc="
  [mod."github.com/prometheus/common"]
    version = "v0.44.0"
    hash = "sha256-8n3gSWKDSJtGfOQgxsiCGyTnUjb5hvSxJi/hPcrE5Oo="
  [mod."github.com/prometheus/procfs"]
    version = "v0.11.1"
    hash = "sha256-yphZ7NZtYC/tb0HVag2T58SuN64Ial9sBo/TdCEQx6Q="
  [mod."github.com/robfig/cron"]
    version = "v1.2.0"
    hash = "sha256-au+MD6DEjpVRAjXWmmJbZRB5IdFfcIqGm6kBkkYNY1s="
  [mod."github.com/rs/zerolog"]
    version = "v1.31.0"
    hash = "sha256-OF4VM+Rv6M5EAaUVD2nOzcbZLQ4b7OAMteyyTqIoU0M="
  [mod."github.com/russross/blackfriday/v2"]
    version = "v2.1.0"
    hash = "sha256-R+84l1si8az5yDqd5CYcFrTyNZ1eSYlpXKq6nFt4OTQ="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.9.0"
    hash = "sha256-xOwGFsYGIxNiurS8Zue8mhlFK/G7U1LVFFrv4vcr1GM="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/stretchr/objx"]
    version = "v0.5.0"
    hash = "sha256-nY4mvP0f0Ry1IKMKQAYNuioA5h4red4mmQqeGZw6EF0="
  [mod."github.com/stretchr/testify"]
    version = "v1.8.4"
    hash = "sha256-MoOmRzbz9QgiJ+OOBo5h5/LbilhJfRUryvzHJmXAWjo="
  [mod."github.com/swaggo/files"]
    version = "v1.0.1"
    hash = "sha256-bNBmpJaM7g1BNwd7VxNIRSdY35NKSXhYHGfnZsSEUZ8="
  [mod."github.com/swaggo/gin-swagger"]
    version = "v1.6.0"
    hash = "sha256-hvX6co7b9Xmhl29ACMvTcD1TTRbI5178r+DRlabgMwY="
  [mod."github.com/swaggo/swag"]
    version = "v1.16.2"
    hash = "sha256-KBC/L2/pIjhrhUbf0jGLVO7J+TKu/MNMXEEibf9iYkk="
  [mod."github.com/syndtr/goleveldb"]
    version = "v1.0.0"
    hash = "sha256-rW7SW6nehede0oMZo4NBatM6Eizbnlb7xYoX/dcDUxA="
  [mod."github.com/tevino/abool/v2"]
    version = "v2.1.0"
    hash = "sha256-rDKv4fnigKLzMAtSG5miExEtmfgOpOOm03Py11McX5k="
  [mod."github.com/twitchyliquid64/golang-asm"]
    version = "v0.15.1"
    hash = "sha256-HLk6oUe7EoITrNvP0y8D6BtIgIcmDZYtb/xl/dufIoY="
  [mod."github.com/ugorji/go/codec"]
    version = "v1.2.11"
    hash = "sha256-hfcj+YsznH6MeERSdIPjSrsM7gbDcIzH/TbgHzYbPww="
  [mod."github.com/urfave/cli/v2"]
    version = "v2.25.7"
    hash = "sha256-/OPbU0DE+xsY6Erz0a3kmzjJPRAXH75FuevmvsaQtw8="
  [mod."github.com/xanzy/go-gitlab"]
    version = "v0.93.1"
    hash = "sha256-tYKSuxkKNaNAkBIn3IaGDkPA0X7P8cG683Mb/FZ94W0="
  [mod."github.com/xeipuuv/gojsonpointer"]
    version = "v0.0.0-20180127040702-4e3ac2762d5f"
    hash = "sha256-OEW9nOR3EeMzvqvqpdAgowpZlbXPLWM0JT+5bwWOxo8="
  [mod."github.com/xeipuuv/gojsonreference"]
    version = "v0.0.0-20180127040603-bd5ef7bd5415"
    hash = "sha256-ZbXA+ASQrTgBQzasUKC9vznrOGpquYyWr+uwpm46fvU="
  [mod."github.com/xeipuuv/gojsonschema"]
    version = "v1.2.0"
    hash = "sha256-1ERBEvxj3pvHkMS2mvmvmYRi8jgAaTquo5hwjDLAEdc="
  [mod."github.com/xrash/smetrics"]
    version = "v0.0.0-20201216005158-039620a65673"
    hash = "sha256-WGHtW/OkLowkqOYIvXpDOpn9wqdH2+Dyx3+rYwpmvzI="
  [mod."github.com/zeebo/blake3"]
    version = "v0.2.3"
    hash = "sha256-ZepnzkvOyicTGL078O1F84q0TzBAouJlB5AMmfsiOIg="
  [mod."go.uber.org/atomic"]
    version = "v1.11.0"
    hash = "sha256-TyYws/cSPVqYNffFX0gbDml1bD4bBGcysrUWU7mHPIY="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."go.uber.org/zap"]
    version = "v1.24.0"
    hash = "sha256-yLzjFbMWnc5b033gcPLGP0KY1xWPJ3sjnUG/RndmC3o="
  [mod."golang.org/x/arch"]
    version = "v0.3.0"
    hash = "sha256-Gus5o3I0+arNjRFglTP5FfCi0NDwKAUT/N3WtdhnLMQ="
  [mod."golang.org/x/crypto"]
    version = "v0.14.0"
    hash = "sha256-UUSt3X/i34r1K0mU+Y5IzljX5HYy07JcHh39Pm1MU+o="
  [mod."golang.org/x/mod"]
    version = "v0.13.0"
    hash = "sha256-qh/YmxS0auZEiKzqdn+v84qs31SpkGIJn9rqKLjdKVU="
  [mod."golang.org/x/net"]
    version = "v0.17.0"
    hash = "sha256-qRawHWLSsJ06QNbLhUWPXGVSO1eaioeC9xZlUEWN8J8="
  [mod."golang.org/x/oauth2"]
    version = "v0.13.0"
    hash = "sha256-mEmRQrh6FMsenT7x406HbZCynBJCHJ4e9u0M3hpG3m4="
  [mod."golang.org/x/sync"]
    version = "v0.4.0"
    hash = "sha256-VCl5IerUva6XZqGXHa0J/r/ewsbOIIP7EBqyh1JGsXY="
  [mod."golang.org/x/sys"]
    version = "v0.13.0"
    hash = "sha256-/+RDZ0a0oEfJ0k304VqpJpdrl2ZXa3yFlOxy4mjW7w0="
  [mod."golang.org/x/term"]
    version = "v0.13.0"
    hash = "sha256-sLN+cjSZN2tfg/Lm9Ae4vYzoXREclMumxfksYFokymQ="
  [mod."golang.org/x/text"]
    version = "v0.13.0"
    hash = "sha256-J34dbc8UNVIdRJUZP7jPt11oxuwG8VvrOOylxE7V3oA="
  [mod."golang.org/x/time"]
    version = "v0.3.0"
    hash = "sha256-/hmc9skIswMYbivxNS7R8A6vCTUF9k2/7tr/ACkcEaM="
  [mod."golang.org/x/tools"]
    version = "v0.14.0"
    hash = "sha256-BC/AesMg7LpIg0/e4a7Ab37rfyP2KaWBFrsonIp+JbE="
  [mod."google.golang.org/appengine"]
    version = "v1.6.8"
    hash = "sha256-decMa0MiWfW/Bzr8QPPzzpeya0YWGHhZAt4Cr/bD1wQ="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20230711160842-782d3b101e98"
    hash = "sha256-VtrLmOh1SLOKKLRmKc/NKR6NR/9DSR4RSq+OXnwmgHY="
  [mod."google.golang.org/grpc"]
    version = "v1.58.3"
    hash = "sha256-YxXO1UAc/+4E0bsSsGSiFNrY3yyR6AIml/1sVY2QJjQ="
  [mod."google.golang.org/protobuf"]
    version = "v1.31.0"
    hash = "sha256-UdIk+xRaMfdhVICvKRk1THe3R1VU+lWD8hqoW/y8jT0="
  [mod."gopkg.in/inf.v0"]
    version = "v0.9.1"
    hash = "sha256-z84XlyeWLcoYOvWLxPkPFgLkpjyb2Y4pdeGMyySOZQI="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."gotest.tools/v3"]
    version = "v3.4.0"
    hash = "sha256-mohKBcuKT29Illk/Gm7Bu5E8QxhRYr6sEGPn/oux65k="
  [mod."k8s.io/api"]
    version = "v0.28.2"
    hash = "sha256-FIplUrrQ0N1jE0NyGhdT4s2d/lvzNn2G/jv1WOFrgcw="
  [mod."k8s.io/apimachinery"]
    version = "v0.28.2"
    hash = "sha256-kfXWigf/vzAPzReZNofH95QlxqmLDbz7Ml659ubn2d0="
  [mod."k8s.io/client-go"]
    version = "v0.28.2"
    hash = "sha256-YDHLVTbAk2T9yF/9pRS/7YxvbE38wdcJLbNHKnWhfoM="
  [mod."k8s.io/klog/v2"]
    version = "v2.100.1"
    hash = "sha256-0pf6/CrK6R6FjlKYjy9ybL3+KaAMNEaWUf0mUs6F5+c="
  [mod."k8s.io/kube-openapi"]
    version = "v0.0.0-20230717233707-2695361300d9"
    hash = "sha256-3d/G/oRLbgBlFFzX8DBd5nQc0EE81rZ9xtHhrQrdA04="
  [mod."k8s.io/utils"]
    version = "v0.0.0-20230406110748-d93618cff8a2"
    hash = "sha256-k++1zQ4f+zJW1DTNUhoPrPJtGszjXTnJFht6xR5YOng="
  [mod."sigs.k8s.io/json"]
    version = "v0.0.0-20221116044647-bc3834ca7abd"
    hash = "sha256-XDBMN2o450IHiAwEpBVsvo9e7tYZa+EXWrifUNTdNMU="
  [mod."sigs.k8s.io/structured-merge-diff/v4"]
    version = "v4.2.3"
    hash = "sha256-v6u6ZqnrEeQ2c7BYkltPKuBFL7+939OT1EbWw0mUE7U="
  [mod."sigs.k8s.io/yaml"]
    version = "v1.3.0"
    hash = "sha256-RVp8vca2wxg8pcBDYospG7Z1dujoH7zXNu2rgZ1kky0="
  [mod."xorm.io/builder"]
    version = "v0.3.13"
    hash = "sha256-nsZZc36EmrjugMWwuw5G3lVvooi50YumFr4OmysrFs4="
  [mod."xorm.io/xorm"]
    version = "v1.3.3"
    hash = "sha256-zO+W4ejFZ90tIzK5BaFBJ9ggRT4RIqbfJszO0z2zdWQ="
