schema = 3

[mod]
  [mod."github.com/bwmarrin/discordgo"]
    version = "v0.0.0-20220708141955-6445b637ad87"
    hash = "sha256-8QVvFW6sLEJ5biGXV9mIM6Sm2pZdEZFeJk1eSJilmQs="
    replaced = "github.com/beeper/discordgo"
  [mod."github.com/gorilla/mux"]
    version = "v1.8.0"
    hash = "sha256-s905hpzMH9bOLue09E2JmzPXfIS4HhAlgT7g13HCwKE="
  [mod."github.com/gorilla/websocket"]
    version = "v1.5.0"
    hash = "sha256-EYVgkSEMo4HaVrsWKqnsYRp8SSS8gNf7t+Elva02Ofc="
  [mod."github.com/lib/pq"]
    version = "v1.10.6"
    hash = "sha256-8EhFwY/9YH5L/fd6l2beOnC3VvpegRAmCCsnDVJBqBM="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.12"
    hash = "sha256-Y1vCt0ShrCz4wSmwsppCfeLPLKrWusc2zM2lUFwDMyI="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.14"
    hash = "sha256-e8zn5eCVh/B1HOP1PGXeXH0bGkIV0vKYP9KLwZni5as="
  [mod."github.com/mattn/go-sqlite3"]
    version = "v1.14.15"
    hash = "sha256-fSrs2sdBKFTAiffBHNnAkN8kDTqiXgm4HNqzJAOF1RM="
  [mod."github.com/rs/zerolog"]
    version = "v1.27.0"
    hash = "sha256-BxQtP2TROeSSpj9l1irocuSfxn55UL4ugzB/og7r8eE="
  [mod."github.com/skip2/go-qrcode"]
    version = "v0.0.0-20200617195104-da1b6568686e"
    hash = "sha256-ST9t4/b7WFXUb8wra4ZYVDNZJGrEykw8dkWhLrxp8F0="
  [mod."github.com/tidwall/gjson"]
    version = "v1.14.1"
    hash = "sha256-v8zb6n6ReFE9hmiwT7tu4avTgLCrelD9lDMMg2My/AI="
  [mod."github.com/tidwall/match"]
    version = "v1.1.1"
    hash = "sha256-M2klhPId3Q3T3VGkSbOkYl/2nLHnsG+yMbXkPkyrRdg="
  [mod."github.com/tidwall/pretty"]
    version = "v1.2.0"
    hash = "sha256-esRQGsn2Ee/CiySlwyuOICSLdqUkH4P7u8qXszos8Yc="
  [mod."github.com/tidwall/sjson"]
    version = "v1.2.4"
    hash = "sha256-Y26Yf4u/GitvqI75f5oucCew6sQjxjRNo77ab58ofVw="
  [mod."github.com/yuin/goldmark"]
    version = "v1.4.12"
    hash = "sha256-x32PnjUc9H2k7ZVP5v+/NWsjWXuGy/Ycse2ERtokq6k="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20220622213112-05595931fe9d"
    hash = "sha256-2c4wvwiQ0DJSJsApfmNoxCxx1siRCiJvW9hhrGlcvds="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20220624214902-1bab6f366d9e"
    hash = "sha256-LKDxEsF5v+SorAzHZGCjcY5dnpZMixI54NqapJy5jtY="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20220520151302-bc2c85ada10a"
    hash = "sha256-3xm4LbLhZjjeb8scaNFRa9zYb8z2fZj+/JBcoyXGPR8="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."maunium.net/go/mauflag"]
    version = "v1.0.0"
    hash = "sha256-fYc/WwqE0ev0dvnu5qGmHJsYiSTuWeOTiAVzmQIKWyY="
  [mod."maunium.net/go/maulogger/v2"]
    version = "v2.3.2"
    hash = "sha256-FlrO1bogPrIzzVzDtIovYyr+1mNk0YaO5hEVv5zovM8="
  [mod."maunium.net/go/mautrix"]
    version = "v0.12.0"
    hash = "sha256-RNKhZ2C2YOhZD7JfL/u7RsNl9GHqJCIjfB4VfWX5hJ4="
