#!/bin/sh
set -euf
export IFS=' '
nix-store -r $DRV_PATH
for f in $DRV_PATH $OUT_PATHS; do
  nix store sign --key-file $HOME/cache.key $f
  nix copy --to "s3://cache-chir-rs?scheme=https&endpoint=s3.us-west-000.backblazeb2.com&secret-key=$HOME/cache.key&multipart-upload=true&compression=zstd&compression-level=15" $f
done

