schema = 3

[mod]
  [mod."dario.cat/mergo"]
    version = "v1.0.0"
    hash = "sha256-jlpc8dDj+DmiOU4gEawBu8poJJj9My0s9Mvuk9oS8ww="
  [mod."github.com/Azure/go-ansiterm"]
    version = "v0.0.0-20230124172434-306776ec8161"
    hash = "sha256-17hCoOE3HBv6cjpcukfBS6/ULgTuoUZ7RNbi5korH2M="
  [mod."github.com/DavidHuie/gomigrate"]
    version = "v0.0.0-20190826182718-4adc4b3de142"
    hash = "sha256-TprT0kezFl+AbDaMvZOeQMNvCyG+5RtRnMGUk4ZUdtk="
  [mod."github.com/Jeffail/gabs"]
    version = "v1.4.0"
    hash = "sha256-Za8Lg0vfQPmuwzu1pUWFwqIoKuHM6TDt1Pe37i4ZOZU="
  [mod."github.com/Microsoft/go-winio"]
    version = "v0.6.1"
    hash = "sha256-BL0BVaHtmPKQts/711W59AbHXjGKqFS4ZTal0RYnR9I="
  [mod."github.com/PuerkitoBio/goquery"]
    version = "v1.8.1"
    hash = "sha256-z2RaB8PVPEzSJdMUfkfNjT616yXWTjW2gkhNOh989ZU="
  [mod."github.com/ajstarks/svgo"]
    version = "v0.0.0-20211024235047-1546f124cd8b"
    hash = "sha256-sPwt5sImKFk949TzUeYEF2UiJDqHxXFJKRL2Y7JWJ6Y="
  [mod."github.com/alioygur/is"]
    version = "v1.0.3"
    hash = "sha256-PDROYkpqujdG0e3yz1xhuSnjP8+U9K46xzBrm41wG6o="
  [mod."github.com/andybalholm/cascadia"]
    version = "v1.3.2"
    hash = "sha256-Nc9SkqJO/ecincVcUBFITy24TMmMGj5o0Q8EgdNhrEk="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/bep/debounce"]
    version = "v1.2.1"
    hash = "sha256-7qHOp4vB0ifEseXXBuSH6W5YNImVcb8PTWSJJAMaGcU="
  [mod."github.com/bwmarrin/snowflake"]
    version = "v0.3.0"
    hash = "sha256-mOU/CgyC9W8XwuinYTPOH69wJY/f+nFVZjZ8lAr9fGM="
  [mod."github.com/cenk/backoff"]
    version = "v2.2.1+incompatible"
    hash = "sha256-aMpsIH8tC5An/Ldb4yTweEbi/4e5gi7InGitPKimxNU="
  [mod."github.com/cenkalti/backoff/v4"]
    version = "v4.2.1"
    hash = "sha256-CKogmPe0pCcAdpztzPwr24rLTJZfq8QVZ9AUduwAcoA="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.2.0"
    hash = "sha256-nPufwYQfTkyrEkbBrpqM3C2vnMxfIz6tAaBmiUP7vd4="
  [mod."github.com/containerd/containerd"]
    version = "v1.7.5"
    hash = "sha256-SQIBdFBh3VWNeHsbzmYswyPEV7Fr1vJrPcoou70fPAg="
  [mod."github.com/cpuguy83/dockercfg"]
    version = "v0.3.1"
    hash = "sha256-ILY8MBdfgIZtuSIGEeXFRiVSDAOLAhdGqr9uq0KSiVk="
  [mod."github.com/cupcake/sigil"]
    version = "v0.0.0-20131127230922-6bf9722f2ae8"
    hash = "sha256-zj78W+DugvlxoiIcjLIbKTb10ZhNz3HjBVLlqsVVWLk="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/dgryski/go-rendezvous"]
    version = "v0.0.0-20200823014737-9f7001d12a5f"
    hash = "sha256-n/7xo5CQqo4yLaWMSzSN1Muk/oqK6O5dgDOFWapeDUI="
  [mod."github.com/dhowden/tag"]
    version = "v0.0.0-20230630033851-978a0926ee25"
    hash = "sha256-zzAeI6sGEE9f8Wr3lg68FEK9pcLsS7YSRXmtqGFUBo0="
  [mod."github.com/didip/tollbooth"]
    version = "v4.0.2+incompatible"
    hash = "sha256-M8K9oYioGBJnSH+Jrf16uwKbC0uacj6I2YiS1bD9W8o="
  [mod."github.com/disintegration/imaging"]
    version = "v1.6.2"
    hash = "sha256-pSeMTPvSkxlthh65LjNYYhPLvCZDkBgVgAGYWW0Aguo="
  [mod."github.com/docker/distribution"]
    version = "v2.8.2+incompatible"
    hash = "sha256-ocVWMRt5ErWdVsj3rsNa/QhizG5b/PCu8LoOlUi24/c="
  [mod."github.com/docker/docker"]
    version = "v24.0.5+incompatible"
    hash = "sha256-c3zzbPWL+p+I+fdhsQwD9ahvVrPmKA8Wno35fFtI1Y0="
  [mod."github.com/docker/go-connections"]
    version = "v0.4.0"
    hash = "sha256-GHNIjOuuNp5lFQ308+nDNwQPGESCVV7bCUxSW5ZxZlc="
  [mod."github.com/docker/go-units"]
    version = "v0.5.0"
    hash = "sha256-iK/V/jJc+borzqMeqLY+38Qcts2KhywpsTk95++hImE="
  [mod."github.com/dsoprea/go-exif/v3"]
    version = "v3.0.1"
    hash = "sha256-Gt1LFNs82CNulAZm5vJB2Evp6cBctPfL4eb1UaboR38="
  [mod."github.com/dsoprea/go-logging"]
    version = "v0.0.0-20200710184922-b02d349568dd"
    hash = "sha256-qc4Nzj7uHl5VRc5Q+iXVCjOmfDQl5wIoiuJKque5jCY="
  [mod."github.com/dsoprea/go-utility/v2"]
    version = "v2.0.0-20221003172846-a3e1774ef349"
    hash = "sha256-s40UVM7/Y7zosud6xvWDRyBEqj1F4fJzSyABdTzK1iE="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.1"
    hash = "sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc="
  [mod."github.com/dyatlov/go-oembed"]
    version = "v0.0.0-20191103150536-a57c85b3b37c"
    hash = "sha256-QX3b7h0mkslDh5QtUU1ZS6f1YH9lGEjz5xdxdmUb7l8="
  [mod."github.com/dyatlov/go-opengraph/opengraph"]
    version = "v0.0.0-20220524092352-606d7b1e5f8a"
    hash = "sha256-Cxi9BjtsbWDh5WIRZ3zdqIJrpmDHydnYRRJOYYPjIGI="
  [mod."github.com/facebookgo/clock"]
    version = "v0.0.0-20150410010913-600d898af40a"
    hash = "sha256-Qh3po2B69wTmUwMS8QcJ3Lz3GpGlN5YPjcVQijXvcvw="
  [mod."github.com/faiface/beep"]
    version = "v1.1.0"
    hash = "sha256-66qAbnJjUjhXofxlGCa6G1+vjQcSTyN/POCZvYzHaQo="
  [mod."github.com/fastly/go-utils"]
    version = "v0.0.0-20180712184237-d95a45783239"
    hash = "sha256-qB9zUQgDG7W2kvbsUSZ+Qb1Lwgd4vBSeIp0+p1JK8Yc="
  [mod."github.com/fatih/color"]
    version = "v1.15.0"
    hash = "sha256-7b+scFVQeEUoXfeCDd8X2gS8GMoWA+HxjK8wfbypa5s="
  [mod."github.com/fogleman/gg"]
    version = "v1.3.0"
    hash = "sha256-Fs2JI0FmF4N5EzXJzGAPZMxZxo6wKyebkN/iBZ9sdNo="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.6.0"
    hash = "sha256-DQesOCweQPEwmAn6s7DCP/Dwy8IypC+osbpfsvpkdP0="
  [mod."github.com/gabriel-vasile/mimetype"]
    version = "v1.4.2"
    hash = "sha256-laV+IkgbnEG07h1eFfPISqp0ctnLXfzchz/CLR1lftk="
  [mod."github.com/getsentry/sentry-go"]
    version = "v0.23.0"
    hash = "sha256-VR6IL+yIc+BV5xBGfPJ7ixsAVzJ/hzuvXmkkAn1cTk4="
  [mod."github.com/go-errors/errors"]
    version = "v1.4.2"
    hash = "sha256-TkRLJlgaVlNxRD9c0ky+CN99tKL4Gx9W06H5a273gPM="
  [mod."github.com/go-redsync/redsync/v4"]
    version = "v4.8.2"
    hash = "sha256-6jYsTKiTqy1X75I0WcaedF/l0wlqAupjWptsertrQMk="
  [mod."github.com/go-sql-driver/mysql"]
    version = "v1.5.0"
    hash = "sha256-DDpwoQ/rAo3Eml3IZYZBu/2ohtGsAPBnxQsuZiKV4BU="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.2"
    hash = "sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c="
  [mod."github.com/golang/freetype"]
    version = "v0.0.0-20170609003504-e2365dfdc4a0"
    hash = "sha256-AHAFBd20/tqxohkWyQkui2bUef9i1HWYgk9LOIFErvA="
  [mod."github.com/golang/geo"]
    version = "v0.0.0-20230421003525-6adc56603217"
    hash = "sha256-j4EFdpNjnCIRM9fFx4zUUipzSdvdAHnC/wmevliJirU="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.3"
    hash = "sha256-svogITcP4orUIsJFjMtp+Uv1+fKJv2Q5Zwf2dMqnpOQ="
  [mod."github.com/google/uuid"]
    version = "v1.3.1"
    hash = "sha256-JxAEAB2bFlGPShFreyOWjUahjaGV3xYS5TpfUOikod0="
  [mod."github.com/gopherjs/gopherjs"]
    version = "v0.0.0-20190430165422-3e4dfb77656c"
    hash = "sha256-kbuMirhXODg0AZZWX4Nlp4VNnD5nNAHa0cX5XNpMbq8="
  [mod."github.com/hajimehoshi/go-mp3"]
    version = "v0.3.4"
    hash = "sha256-h6l0PuIS0h1zdB8MEqHTTgg8dE6nL6PSOt583ymaPnA="
  [mod."github.com/hashicorp/errwrap"]
    version = "v1.1.0"
    hash = "sha256-6lwuMQOfBq+McrViN3maJTIeh4f8jbEqvLy2c9FvvFw="
  [mod."github.com/hashicorp/go-hclog"]
    version = "v1.5.0"
    hash = "sha256-u3Jqg7Qex11IZ7vbk4hRGgLy6e0cF70CCx7ERF0GUHo="
  [mod."github.com/hashicorp/go-multierror"]
    version = "v1.1.1"
    hash = "sha256-ANzPEUJIZIlToxR89Mn7Db73d9LGI51ssy7eNnUgmlA="
  [mod."github.com/hashicorp/go-plugin"]
    version = "v1.5.0"
    hash = "sha256-y0gCsjgYr547ITwHlitD8Eueh8LYcjdnmRpk2r+lNcY="
  [mod."github.com/hashicorp/yamux"]
    version = "v0.1.1"
    hash = "sha256-jr4ZFM3XHSwGoZcRcmmdGTq4IqxBTnimojIPDgK0USU="
  [mod."github.com/icza/bitio"]
    version = "v1.1.0"
    hash = "sha256-CtV/dr1L46cZ65EnK9DrBduZCaMnTGf4N2MnElCymtM="
  [mod."github.com/jehiah/go-strftime"]
    version = "v0.0.0-20171201141054-1d33003b3869"
    hash = "sha256-+4WOjV+F2BXgKmdfYvuSkfQAKOZlFo8eZrnCT+xT3xQ="
  [mod."github.com/jfreymuth/oggvorbis"]
    version = "v1.0.5"
    hash = "sha256-jphTCaPr34ZT9Id4ZZ6zU9Vnxzy6cTjCwjpQ819eGV0="
  [mod."github.com/jfreymuth/vorbis"]
    version = "v1.0.2"
    hash = "sha256-gVS+/PZ5pDnswpTQNZILcrx5ZNq9ShXd6vXn7Jabes4="
  [mod."github.com/jonboulle/clockwork"]
    version = "v0.1.0"
    hash = "sha256-dEV9aGzJRIrYfPpuJux3guJNvZGi+5dfseGurZqGHd8="
  [mod."github.com/json-iterator/go"]
    version = "v1.1.12"
    hash = "sha256-To8A0h+lbfZ/6zM+2PpRpY3+L6725OPC66lffq6fUoM="
  [mod."github.com/julienschmidt/httprouter"]
    version = "v1.3.0"
    hash = "sha256-YVbnyFLVZX1mtqcwM1SStQdhcQsPHyi1ltpOrD3w2qg="
  [mod."github.com/k3a/html2text"]
    version = "v1.2.1"
    hash = "sha256-6raeYlNE68D/vEX7m6wurFrTIRPaj+SOoqo57NOQLl0="
  [mod."github.com/kettek/apng"]
    version = "v0.0.0-20220823221153-ff692776a607"
    hash = "sha256-VuxcQDPJsmSpueFu9ECqG/EIr29eDALA1iRpl2pquzI="
  [mod."github.com/klauspost/compress"]
    version = "v1.16.7"
    hash = "sha256-8miX/lnXyNLPSqhhn5BesLauaIAxETpQpWtr1cu2f+0="
  [mod."github.com/klauspost/cpuid/v2"]
    version = "v2.2.5"
    hash = "sha256-/M8CHNah2/EPr0va44r1Sx+3H6E+jN8bGFi5jQkLBrM="
  [mod."github.com/lestrrat/go-envload"]
    version = "v0.0.0-20180220120943-6ed08b54a570"
    hash = "sha256-O+xFK7J0d+cgv9N4pI/Nunk89FVQ3Zmywn1QfBc8pH4="
  [mod."github.com/lestrrat/go-file-rotatelogs"]
    version = "v0.0.0-20180223000712-d3151e2a480f"
    hash = "sha256-A89P/ThMyvrYoj7Yhq/3PG8MM7KDQE+pWf4F3WHjuoo="
  [mod."github.com/lestrrat/go-strftime"]
    version = "v0.0.0-20180220042222-ba3bf9c1d042"
    hash = "sha256-Wd3GYo14taUxeZbqogdt6y8aPikCTyghK20WPamH5JU="
  [mod."github.com/lib/pq"]
    version = "v1.10.9"
    hash = "sha256-Gl6dLtL+yk6UrTTWfas43aM4lP/pNa2l7+ITXnjQyKs="
  [mod."github.com/magiconair/properties"]
    version = "v1.8.7"
    hash = "sha256-XQ2bnc2s7/IH3WxEO4GishZurMyKwEclZy1DXg+2xXc="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.19"
    hash = "sha256-wYQqGxeqV3Elkmn26Md8mKZ/viw598R4Ych3vtt72YE="
  [mod."github.com/mattn/go-sqlite3"]
    version = "v2.0.3+incompatible"
    hash = "sha256-+zdGqThUb7if9JAiO+6s6KXBeuT322JhfcityvdrxD4="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.4"
    hash = "sha256-uovu7OycdeZ2oYQ7FhVxLey5ZX3T0FzShaRldndyGvc="
  [mod."github.com/mewkiz/flac"]
    version = "v1.0.8"
    hash = "sha256-CdgX5s+WyTs7qZKJZMrp5c5VVoalBxYTlmmKiSqIoR0="
  [mod."github.com/mewkiz/pkg"]
    version = "v0.0.0-20230226050401-4010bf0fec14"
    hash = "sha256-vpPhgYcMQIaDd50OdQZvDitV73oBNGJhCNYVt1FKIX4="
  [mod."github.com/minio/md5-simd"]
    version = "v1.1.2"
    hash = "sha256-vykcXvy2VBBAXnJott/XsGTT0gk2UL36JzZKfJ1KAUY="
  [mod."github.com/minio/minio-go/v7"]
    version = "v7.0.63"
    hash = "sha256-6jIVszEtpMlpipTccqitiSC0VomVzkkZyfBoSHbCoek="
  [mod."github.com/minio/sha256-simd"]
    version = "v1.0.1"
    hash = "sha256-4hfGDIQaWq8fvtGzHDhoK9v2IocXnJY7OAL6saMJbmA="
  [mod."github.com/mitchellh/go-testing-interface"]
    version = "v1.14.1"
    hash = "sha256-TMGi38D13BEVN5cpeKDzKRIgLclm4ErOG+JEyqJrN/c="
  [mod."github.com/moby/patternmatcher"]
    version = "v0.6.0"
    hash = "sha256-ny3L8ktj8cyN41CEJhaRT74Vi8HpXXsbTvlrw/Tl5+g="
  [mod."github.com/moby/sys/sequential"]
    version = "v0.5.0"
    hash = "sha256-A29wOMXw/O8L5Kmu3UNb9s9go2Vya8qFEYtsYrg3Rzo="
  [mod."github.com/moby/term"]
    version = "v0.5.0"
    hash = "sha256-jy0kbkeUsr0KoiE33WLxNAgYXZIERKR2O5+saXBwdD8="
  [mod."github.com/modern-go/concurrent"]
    version = "v0.0.0-20180306012644-bacd9c7ef1dd"
    hash = "sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo="
  [mod."github.com/modern-go/reflect2"]
    version = "v1.0.2"
    hash = "sha256-+W9EIW7okXIXjWEgOaMh58eLvBZ7OshW2EhaIpNLSBU="
  [mod."github.com/morikuni/aec"]
    version = "v1.0.0"
    hash = "sha256-5zYgLeGr3K+uhGKlN3xv0PO67V+2Zw+cezjzNCmAWOE="
  [mod."github.com/oklog/run"]
    version = "v1.1.0"
    hash = "sha256-U4IS0keJa4BSBSeEBqtIV1Zg6N4b0zFiKfzN9ua4pWQ="
  [mod."github.com/opencontainers/go-digest"]
    version = "v1.0.0"
    hash = "sha256-cfVDjHyWItmUGZ2dzQhCHgmOmou8v7N+itDkLZVkqkQ="
  [mod."github.com/opencontainers/image-spec"]
    version = "v1.1.0-rc4"
    hash = "sha256-rsc3wL80rmQhf4tiHQ0RJAcTsbdzqqS3TIlK9BWzOKQ="
  [mod."github.com/opencontainers/runc"]
    version = "v1.1.9"
    hash = "sha256-zJI1/cRfG9PqX/je79AbS/dSmvSHv1p8Rs3qN0g93Fs="
  [mod."github.com/panjf2000/ants/v2"]
    version = "v2.8.1"
    hash = "sha256-SxPFjCOjG4uvUf1XxX0w6aoyNBKbuzXTykFLaNxrgnQ="
  [mod."github.com/patrickmn/go-cache"]
    version = "v2.1.0+incompatible"
    hash = "sha256-+i3/Cd9byb1q926jszLjadiUMUeux0VyGKnmP20EAoA="
  [mod."github.com/peterbourgon/g2s"]
    version = "v0.0.0-20170223122336-d4e7ad98afea"
    hash = "sha256-NIVsrq1z2UEvuVTHVIptWDn0MYx4jMyk707K7QNLiq8="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.16.0"
    hash = "sha256-P/b4/8m1ztF0fCLSJ+eRXN74Bncx2vjOJx7nFl2QEg4="
  [mod."github.com/prometheus/client_model"]
    version = "v0.4.0"
    hash = "sha256-4P0sPWpxa69gGM6zm3dA06cH6twaeopq22VVDJjucHA="
  [mod."github.com/prometheus/common"]
    version = "v0.44.0"
    hash = "sha256-8n3gSWKDSJtGfOQgxsiCGyTnUjb5hvSxJi/hPcrE5Oo="
  [mod."github.com/prometheus/procfs"]
    version = "v0.11.1"
    hash = "sha256-yphZ7NZtYC/tb0HVag2T58SuN64Ial9sBo/TdCEQx6Q="
  [mod."github.com/redis/go-redis/v9"]
    version = "v9.1.0"
    hash = "sha256-dXHN2blZPDbSgp40g2kQ7KXyul75M6jCvB/y/FHvRH4="
  [mod."github.com/rifflock/lfshook"]
    version = "v0.0.0-20180920164130-b9218ef580f5"
    hash = "sha256-LHemSy/AaUcajEm9mdPjw6+nJht81dcqnYCh5ySTuHM="
  [mod."github.com/rs/xid"]
    version = "v1.5.0"
    hash = "sha256-u0QLm2YFMJqEjUhpWcLwfoS9lNHUxc2A79MObsqVbVU="
  [mod."github.com/rubyist/circuitbreaker"]
    version = "v2.2.1+incompatible"
    hash = "sha256-6qlPpfrp0grghKbwnRBh3azjyJSjS2e2FPhgz3Q76DU="
  [mod."github.com/ryanuber/go-glob"]
    version = "v1.0.0"
    hash = "sha256-YkMl1utwUhi3E0sHK23ISpAsPyj4+KeXyXKoFYGXGVY="
  [mod."github.com/sabhiram/go-gitignore"]
    version = "v0.0.0-20210923224102-525f6e181f06"
    hash = "sha256-A1aJFlcPRQvDqdJmEwpzhftR8C1Kzv1hXPszq8eO76Q="
  [mod."github.com/saintfish/chardet"]
    version = "v0.0.0-20230101081208-5e3ef4b5456d"
    hash = "sha256-JXlHMCbXB8iRQ9wQBGCeTjDSfgaBwUVOpvcjj0iVn5A="
  [mod."github.com/sebest/xff"]
    version = "v0.0.0-20210106013422-671bd2870b3a"
    hash = "sha256-t7Gdp7S71Koej5Njg3jOo5vwyj02tJCbJjrq/vZGOho="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.9.3"
    hash = "sha256-EnxsWdEUPYid+aZ9H4/iMTs1XMvCLbXZRDyvj89Ebms="
  [mod."github.com/smartystreets/assertions"]
    version = "v1.0.0"
    hash = "sha256-sI2UUdq1+H+rcLysKDXDeaXi1Pz+zq28d/o/mV0c2wE="
  [mod."github.com/stretchr/testify"]
    version = "v1.8.4"
    hash = "sha256-MoOmRzbz9QgiJ+OOBo5h5/LbilhJfRUryvzHJmXAWjo="
  [mod."github.com/strukturag/libheif"]
    version = "v1.16.2"
    hash = "sha256-jR0a6nvzviu3YtN+0V4mj6s7ZiwQJlg6BUSaI5GSlFs="
  [mod."github.com/t2bot/go-singleflight-streams"]
    version = "v0.0.8"
    hash = "sha256-YG78j81YNvsqS1hrJScmaz4kNF+O3TAnFsGgVzDKna4="
  [mod."github.com/t2bot/go-typed-singleflight"]
    version = "v0.0.3"
    hash = "sha256-gDeRUn27fWmdPmBaVR8aly2rRmreVxmWeUM/P7N4PZI="
  [mod."github.com/t2bot/gotd-contrib"]
    version = "v0.0.0-20230907202504-d21987ea2957"
    hash = "sha256-UQB0iEYhOlTA0TvkZwKgYm0UKQYDqx5qlOzON4Q5tH0="
  [mod."github.com/t2bot/pgo-fleet/embedded"]
    version = "v1.0.1"
    hash = "sha256-UrNOX5SXttFPLdVVpzslPFBb4T+xDI359vxqsBS7TEY="
  [mod."github.com/tebeka/strftime"]
    version = "v0.1.3"
    hash = "sha256-ahLbzsDylxmyGMzcUGePJCCR/qjtNPDQ2R21C38ydi8="
  [mod."github.com/testcontainers/testcontainers-go"]
    version = "v0.23.0"
    hash = "sha256-ItMwMkJa//CARErkX+27koux0MmQ9nOXEvD5Ck97c/Q="
  [mod."github.com/testcontainers/testcontainers-go/modules/postgres"]
    version = "v0.23.0"
    hash = "sha256-/A4hZV/MkOgbnin1fIu4jR9aPD0wcKdRzOcm/8QaGYQ="
  [mod."golang.org/x/crypto"]
    version = "v0.12.0"
    hash = "sha256-Wes72EA9ICTG8o0nEYWZk9xjpqlniorFeY6o26GExns="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20230817173708-d852ddb80c63"
    hash = "sha256-mXqobW94++1Ei5cFMyb9rVkA+lyc7kqj0tz7JOFIF4w="
  [mod."golang.org/x/image"]
    version = "v0.12.0"
    hash = "sha256-ttx1gCoWia/Nhhq9t6a2rEXI1gCu5UCLmECIbVtqbp8="
  [mod."golang.org/x/mod"]
    version = "v0.12.0"
    hash = "sha256-M/oXnzm7odpJdQzEnG6W0pNYtl0uhOM/l7qgfGVpU2M="
  [mod."golang.org/x/net"]
    version = "v0.14.0"
    hash = "sha256-QScKgO7lBWOsd0Y31wLRzFETv3tjqdB/eRQWW5q7aV4="
  [mod."golang.org/x/sync"]
    version = "v0.3.0"
    hash = "sha256-bCJKLvwExhYacH2ZrWlZ38lr1d6oNenNt2m1QqDCs0o="
  [mod."golang.org/x/sys"]
    version = "v0.12.0"
    hash = "sha256-Ht/PhBJGWNBg4ksmdUu4+7hJjFypSwoUN/8DJricd+0="
  [mod."golang.org/x/term"]
    version = "v0.12.0"
    hash = "sha256-NFko0uqv/r2VxrbSgS1IwWzaWQK3RZuk0MvUV+qxIsc="
  [mod."golang.org/x/text"]
    version = "v0.13.0"
    hash = "sha256-J34dbc8UNVIdRJUZP7jPt11oxuwG8VvrOOylxE7V3oA="
  [mod."golang.org/x/time"]
    version = "v0.3.0"
    hash = "sha256-/hmc9skIswMYbivxNS7R8A6vCTUF9k2/7tr/ACkcEaM="
  [mod."golang.org/x/tools"]
    version = "v0.12.1-0.20230815132531-74c255bcf846"
    hash = "sha256-j6UwNGtMrqfwNyU4CImmqBYNkKjSDioYc+iJy3GKpw8="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20230822172742-b8732ec3820d"
    hash = "sha256-1kP7lqQ+fKtARDzTrRNob0owX4GsUnxzOwLyBZSmHOc="
  [mod."google.golang.org/grpc"]
    version = "v1.57.0"
    hash = "sha256-hP6alxFu+pcLI4gT3idzEMYNp+DbU3P4xhkpIqGCPXg="
  [mod."google.golang.org/protobuf"]
    version = "v1.31.0"
    hash = "sha256-UdIk+xRaMfdhVICvKRk1THe3R1VU+lWD8hqoW/y8jT0="
  [mod."gopkg.in/ini.v1"]
    version = "v1.67.0"
    hash = "sha256-V10ahGNGT+NLRdKUyRg1dos5RxLBXBk1xutcnquc/+4="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
