name: update
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "49 4 * * *"
jobs:
  flake-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nixcache:8KKuGz95Pk4UJ5W/Ni+pN+v+LDTkMMFV4yrGmAYgkDg= hydra.nixos.org-1:CNHJZBh9K4tP3EKF6FkkgeVYsS3ohTl+oS0Qa8bezVs= chir-rs:AnwyFacopHSkprD6aXY4/R3J9JYzTbV2rosJCBPaB28=
            experimental-features = nix-command flakes ca-derivations
            post-build-hook = ${{ github.workspace }}/scripts/post-build-hook
            substituters = https://attic.chir.rs/chir-rs/ https://cache.nixos.org/
      - name: Download attic
        run: nix build github:DarkKirb/nix-packages#attic-client
      - name: Set up secrets
        run: nix run github:DarkKirb/nix-packages#attic-client -- login attic-server https://attic-nocdn.chir.rs/ "$ATTIC_TOKEN"
        env:
          ATTIC_TOKEN: ${{secrets.ATTIC_TOKEN}}
      - name: Update flake.lock
        run: nix flake update
      - name: Run update script
        run: yes '' | nix-shell ./scripts/update.nix --argstr max-workers 1
      - name: Format
        run: nix fmt
      - name: Delete secrets
        run: |
          rm ~/cache.key
      - name: Create PR
        uses: peter-evans/create-pull-request@v4.2.0
        with:
          commit-message: Update nix-packages
          author: Github Actions <github-actions@users.noreply.github.com>
          committer: Github Actions <github-actions@users.noreply.github.com>
          title: Automated updates for nix-packages
          body: Automated updates
          assignees: darkkirb
          reviewers: darkkirb
